### ISSUE TITLE
FileNotFoundError in process_rsmas.py

### ISSUE THREAD

**Issue by Ovec8hkin** [geodesymiami/rsmas_insar#102]
FileNotFoundError: [Errno 2] No such file or directory: '/projects/scratch/insarlab/jaz101/unittestGalapagosSenDT128/PYSAR'

Does someone known why this is the case? This only happens in the `run_operations_new` branch, but it and `master` are both up-to-date with each other.

To reproduce:

```
git checkout run_operations_new
process_rsmas.py /nethome/jaz101/test/test4/rsmas_insar/samples/unittestGalapagosSenDT128.template --startmakerun --submit &
```

**Comment by falkamelung** [comment]
Did you try on your master? Can you go back to it? On my master it works fine

------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 19, 2019, at 10:46 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #102<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeodesymiami%2Frsmas_isce%2Fissues%2F102&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C6e84e4a9b9624b408a2b08d6ace69b98%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636886503792574300&sdata=cuAVnM%2Fexsv5k%2BKkkBWuXHBDkHkNC2hiTqipCZvD0Zc%3D&reserved=0> to @falkamelung<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C6e84e4a9b9624b408a2b08d6ace69b98%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636886503792584305&sdata=E9XDDYNUUfcxDTAIeYqu6CBKgThCb%2BZtleNgoBvyKm4%3D&reserved=0>.

**Comment by Ovec8hkin** [comment]
It works on master. I merged master into my development branch, and it doesn't work there.

**Comment by falkamelung** [comment]
Yeah, something else is broken. If you just merge into master it will be easier to find.
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 19, 2019, at 10:52 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


It works on master. I merged master into my development branch, and it doesn't work there.

**Comment by falkamelung** [comment]
I mean run_operations.py
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 19, 2019, at 10:54 PM, Amelung, Falk C <famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>> wrote:

Yeah, something else is broken. If you just merge into master it will be easier to find.
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu<https://nam01.safelinks.protection.outlook.com/?url=http%3A%2F%2Finsarmaps.miami.edu&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Cf5cbb32af88b493bd67108d6ace7bf38%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636886508677998949&sdata=VKPCDN8cp0YrfAiIkLii0%2FPxOullrvgT5Lp9uRGE%2FAw%3D&reserved=0>




On Mar 19, 2019, at 10:52 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


It works on master. I merged master into my development branch, and it doesn't work there.

**Comment by Ovec8hkin** [comment]
I don't want to merge run_operations into master yet because there are other untested parts of run_operations that I need to verify work before its ready for merge.

**Comment by falkamelung** [comment]
But you don’t break anything as the current version does not work anyway???
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 19, 2019, at 10:55 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't want to merge run_operations into master yet because there are other untested parts of run_operations that I need to verify work before its ready for merge.

**Comment by Ovec8hkin** [comment]
Im just going to make a new test environment, and merge run_operations_new there and check if it works.

**Comment by falkamelung** [comment]
I copied run_operations over and got the following errror, but did not try any further
```
             = yes                                               # [yes / no], auto for yes, save geocoded velocity to Google Earth KMZ file\n", 'testKilaueaSenD87': None, 'testKilaueaSenAT124': None, 'testAgungSenDT32': None, 'testAgungSenAT156': None, 'testLombokSenDT32': None, 'testLombokSenAT156': None, 'testCotopaxiSenAT120': None, 'testChilesSenAT120': None, 'testGalerasSenAT120': None}
2019-03-20 09:54:53,427 - INFO - Finished generating template files
Traceback (most recent call last):
  File "/nethome/famelung/test/test1/rsmas_insar/sources/rsmas_isce/run_operations.py", line 296, in <module>
    run_operations(sys.argv[1:])
  File "/nethome/famelung/test/test1/rsmas_insar/sources/rsmas_isce/run_operations.py", line 230, in run_operations
    datasets = [putils.get_project_name(template) for template in template_files]
TypeError: 'NoneType' object is not iterable

[1]+  Exit 1                  run_operations.py --sheet_id 1CPg29RhjBVdWLdTk50RyoX0Fk0Ab-piZMMwJRvHIipc
```
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 20, 2019, at 9:05 AM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


Im just going to make a new test environment, and merge run_operations_new there and check if it works.

**Comment by Ovec8hkin** [comment]
I merged the `run_operations_new` branch with `master` and I get the same error

**Comment by Ovec8hkin** [comment]
I isolated the problem. Apparently the `sys.exit(0)` command on line 276 of `create_batch.py` has some odd functionality that, when removed, causes the above errors to occur in `process_rsmas.py`. However, I've found that leaving it there causes error in `run_operations.py`. I will look for other solutions to the problems it cause sin `run_operations.py`
