### ISSUE TITLE
Parser Update: Refactoring Parsing

### ISSUE THREAD

**Issue by gravelcycles** [geodesymiami/rsmas_insar#109]
We currently have 2 functions for parsing (`create_parser` and `command_line_parse`). Why not make it one function?

Also, the most relevant functions should be at the top of a file and the helper functions should be at the bottom. In that spirit, parser functions should be moved to the bottom of the code.

Thoughts?

**Comment by yunjunz** [comment]
The benefits of separating them:
1. to be able to share the same parser among different scripts, for example, the majority of the parsing function in `view.py` and `tsview.py` are from `pysar/utils/plot.py`
https://github.com/insarlab/PySAR/blob/master/pysar/utils/plot.py#L550
2. `command_line_parse` can be focused more on the parsing and input arguments checking.

As for the location within the file, I don't have a preference. I just used the same as I saw from ISCE code. I do use some global variable `TEMPLATE` and `EXAMPLE` during the helper function, and thought it's better to keep them close.
https://github.com/insarlab/PySAR/blob/master/pysar/geocode.py
