### ISSUE TITLE
Add Metadata Items to TIFF File

### ISSUE THREAD

**Issue by Ovec8hkin** [geodesymiami/rsmas_insar#114]
Please add the following information to the TIFF files that are generated:

- Satellite Name
- Satellite Ascending/Descending
- Image Type (geo_backscatter, ortho_backscatter, geo_coherence, etc.)
- Date (YYYYMMDD format)
- Volcano ID from Smithsonian
- Volcano Name from Smithsonian?

**Comment by falkamelung** [comment]
Here what we have:
https://github.com/insarlab/PySAR/wiki/HDF-EOS5
https://github.com/insarlab/PySAR/wiki/Attributes#attributes-generated-by-pysar-automatically

**Comment by mirzaees** [comment]
@Ovec8hkin 

This is a link to new sample products (Ortho backscatter):
https://www.dropbox.com/sh/r8prqzunuziz3dl/AABENSuf1TZbEH4Lem5Clsy2a?dl=0

Metadata are attached like this:

    Date=20170101
    Image Type=Ortho_BackScatter
    Mode=Desc
    SAT=S1

@falkamelung
