### ISSUE TITLE
Email notification on pegasus and other platforms refactor

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#119]
Here what FA plans to improve emailing: 
- introduce environment variable `MAIL_HOST` (similar to `DOWNLOAD_HOST`, which can take the values `local` or `pegasus.ccs.miami.edu`. If `MAIL_HOST` is not `local`, then there will be an `ssh` into `MAIL_HOST`.
- create a function `send_email_notification(subject_line, message_body, attachment_list, addressee_list)`

***Questions:*** 
- I plan to use the built-in mail function (as we currently do), Are there any benefits to use the python email modules? 
- any other thoughts?

Could be useful:
https://realpython.com/courses/sending-emails-python/

**Comment by Ovec8hkin** [comment]
Lets think carefully about this and do it right. Im sure there are some good python modules for sending emails, and I think it would be better to use those rather than shooting off `mail` commands like we do now. How high priority is this?

**Comment by falkamelung** [comment]
Thank you. I may do it as early as later this week if  it turns out that we need it. But I would do a quick-and-dirty job so that it can be refactored. This could be something for Alex to start with.

------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Apr 15, 2019, at 10:23 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


Lets think carefully about this and do it right. Im sure there are some good python modules for sending emails, and I think it would be better to use those rather than shooting off mail commands like we do now. How high priority is this?

**Comment by gravelcycles** [comment]
What are the other ways we could do this? I'm doing this as a way around jumping to the first idea we come up with and going with that. (Idea shamelessly stolen from Philosophy of Software Design). So let's not reject or accept ideas based on first glance but think about their value.

One way I can think of:
Why not have `SCHEDULER = {'LSF', 'PBS', 'NOSCHEDULER'}` and `HOST = {'PEGASUS-LOGIN', 'PEGASUS-COMPUTE', 'JETSTREAM', 'AWS-EC2'}` variables and then based on those, we can have a mail function that uses the `HOST` variable to determine how to send the email.

**Comment by gravelcycles** [comment]
I'm okay with using the Linux `mail` command as it should be pretty consistent. But, as you know, I'm totally okay with using a Python module for this, as long as it's well documented, supported, and in active use/development.

**Comment by falkamelung** [comment]
Unfortunately, on pegasus mail is very unreliable. Sometime messages never arrive, sometime they arrive weeks later.
Yeah, it would be good to have one *defaults file for `HOST`-dependent variables and one for `JOBQUEUE`-related variables
