### ISSUE TITLE
Need script to remove zero-lines files

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#12]
We need a little function that detects and removes run_*.e files that erroneously contain a line counter although it is not an error to be inserted into process_sentinel after the stackSentinel processing (let's discuss wednesday)

remove_error_files_containing_line_counter.py  [dir]
remove_error_files_containing_line_counter.py   

 ls -l run_10_filter_coherence*e
-rw-rw----+ 1 famelung insarlab 13608 Oct  4 03:34 run_10_filter_coherence_1000_17816645.e

cat run_10_filter_coherence_1000_17816645.e
line:  1100//login3/projects/scratch/insarlab/dwg11/GalapagosSenDT128/run_files

**Comment by Ovec8hkin** [comment]
Could you be more specific about what you what done? What directory are we talking about? What files name scheming are we using? Should this be a stand alone script? Should it run universally from any directory? What parameters should it be given when ran?

**Comment by falkamelung** [comment]
I will explain friday.
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://yyy.rsmas.miami.edu/users/famelung/
InSAR data:
http://insarmaps.miami.edu

On Oct 10, 2018, at 3:55 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you be more specific about what you what done? What directory are we talking about? What files name scheming are we using? Should this be a stand alone script? Should it run universally from any directory? What parameters should it be given when ran?

**Comment by falkamelung** [comment]
done
