### ISSUE TITLE
Strategy to isolate ISCE from Pegasus errors

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#120]
Thoughts on this plan?

The main issue with our codebase are irreproducible ISCE failures.  They could be due to pegasus issues, ISCE bugs or user did something stupid. We need to be able to reliably isolate ISCE bugs in order to request fixes. (First modify  installation to use conda install isce once run_files are working)

Strategy:
- Before processing create a directory listing `dir_listing_$job_id` to make sure that we start out with the same files

After each create_batch run do the following (in `execute_stacksentinel_run_files`:
1.  Check for `disk full` messages in *.o *.e files
2. Remove zero-size and zero-file-length error files using `remove_zero_size_or_length_error_files`
3. Identify failed/exited jobs  using `raise_exception_if_job_exited` function except for wall time exceedance in phase-unwrapping step (send notification if that happens).
4. Create a function `raise_exception_if_fatal_error` which reads the *.e file. It will raise an exception for fatal errors. Non-fatal errors will_be identified by strings given in a file `defaults/skip_exception_patterns.yaml` of the form:
  
```
skip_exception:
pairs_misreg: FileNotFoundError: [Errno 2] No such file or directory
```

This *yaml file will be eventually a summary of non-fatal ISCE, PYSAR, and geodmod errors, encouraging the authors to correct them.

**Comment by 2gotgrossman** [comment]
Are steps 3. and 4. repeats?

**Comment by falkamelung** [comment]
yes, it was

**Comment by falkamelung** [comment]
When a job fails because of walltime exceedance, we get the message below and the jobs should be restarted. The natural thing is to restart with a long walltime (50% longer), but the thing is that some jobs run very, very slow because the node is used for something else (by somebody else, most likely). Not sure how to figure this out. Maybe from the CPU time/walltime ratio. But I don't really understand what CPU time is as it is sometimes longer than the walltime (we use use one  CPU!)

```
TERM_RUNLIMIT: job killed after reaching LSF run time limit.
Exited with exit code 140.
```
Here some wall

**Comment by mirzaees** [comment]
I think this issue is `Done`.
if a step is failed or job is exited for some reason, the process will stop creating an error file that explains where it has stopped. in *.o files, the reason of exit jobs can be found, whether it is from pegasus or scripts
