### ISSUE TITLE
simplifying sentinelStack.subswath field

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#129]
ISCE requires different format for the subswath depending on whether one or two  swaths are given:
```
sentinelStack.subswath              = 2
sentinelStack.subswath              = '2 3' 
sentinelStack.subswath              = '1 2 3'
``` 
I get frequently failures  because I  forget and give the wrong format. I think we should modify so that it converts any of those options below in the options above.
```
sentinelStack.subswath              = 1
sentinelStack.subswath              = 2 3 
sentinelStack.subswath              = 1 2 3
sentinelStack.subswath              = '2'
sentinelStack.subswath              = '2 3' 
sentinelStack.subswath              = '1 2 3' 
``` 
Same for
```
sentinelStack.boundingBox      = '-0.7 -0.6 -91.7 -90.9'
```
I am considering to add to `dataset_template` functions `reformat_subswath_string` and `reformat_boundingBox_string`. 

Thoughts, suggestions (e.g. on function naming)?

**Comment by mirzaees** [comment]
I suppose this can be solved by adding '.strip("'")' to each template values while we are reading it. 
I fixed some of these issues and the function 'create_or update_template' in 'using_runfiles' branch.
please test using run files.

The only problem with new configuration would be run_operations.py that I think it won't run properly and needs some update
