### ISSUE TITLE
DEM generation errors:  need function check_USGS_server

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#135]
I occasionally get the error below from dem_rsmas.py. This could be because the USGS server is down (I believe I read somewhere that they have maintenance on Wednesday, but I am not sure).   Is there an easy way check whether the server  is alive? We could have `USGS_dem_server_alive` or `check_USGS_server`.  What command to to use to check?   I @2gotgrossman or @Ovec8hkin  can tell me the command I can build this in myself.

```
error in dem.py: Tiles are missing. Ocean???
2019-04-24 11:06:12,364 - ERROR - ERROR while making DEM
Traceback (most recent call last):
  File "/nethome/famelung/test/test2/rsmas_insar/rinsar/process_rsmas.py", line 146, in <module>
    process(inps)
  File "/nethome/famelung/test/test2/rsmas_insar/rinsar/process_rsmas.py", line 75, in process
    prs.create_or_copy_dem(inps, inps.work_dir, inps.template, inps.custom_template_file)
  File "/nethome/famelung/test/test2/rsmas_insar/rinsar/_processSteps.py", line 325, in create_or_copy_dem
    raise Exception('ERROR while making DEM')
Exception: ERROR while making DEM
//login3/projects/scratch/insarlab/famelung/testDarbandikhanSenDT79[1007] vi /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/testDarbandikhanSenDT79.template
//login3/projects/scratch/insarlab/famelung/testDarbandikhanSenDT79[1008] cat log
20190424:104337 * ##### NEW RUN #####
20190424:104337 * process_rsmas.py /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/testDarbandikhanSenDT79.template
20190424:104337 * download_rsmas.py /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/testDarbandikhanSenDT79.template
20190424:104353 * download_ssara_rsmas.py /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/testDarbandikhanSenDT79.template
20190424:110006 * download_asfserial_rsmas.py /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/testDarbandikhanSenDT79.template
20190424:110607 * dem_rsmas.py /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/testDarbandikhanSenDT79.template
20190424:110607 * dem_rsmas.py /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/testDarbandikhanSenDT79.template
//login3/projects/scratch/insarlab/famelung/testDarbandikhanSenDT79[1009] ll DEM
ls: cannot access DEM: No such file or directory
//login3/projects/scratch/insarlab/famelung/testDarbandikhanSenDT79[1010] vi /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/testDarbandikhanSenDT79.template
//login3/projects/scratch/insarlab/famelung/testDarbandikhanSenDT79[1011] dem_rsmas.py /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/testDarbandikhanSenDT79.template
YO WHATS GOOD???
20190424:203842 * dem_rsmas.py /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/testDarbandikhanSenDT79.template
DEM generation using ISCE
20190424:203842 * dem.py -a stitch -b 34 36 44 48 -c -u https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL1.003/2000.02.11/
```

**Comment by Ovec8hkin** [comment]
What about this error message leads you to believe that the USGS server is down?

**Comment by falkamelung** [comment]
Nothing from the message. This is what we need, a function to check whether there could be a server problem. I ran the same command today and there was no problem.

I had this before. I processed something on a Wednesday (at a certain time?) , got failures, and spend hours trying to figure out why it failed.  The next day it worked.

As I said, at some time I looked into some USGS servers and found something on occasional downtime at a certain hour on wednesdays….. This is odd but maybe this what they do.



------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Apr 25, 2019, at 11:12 AM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


What about this error message leads you to believe that the USGS server is down?

**Comment by gravelcycles** [comment]
So knowing if a server is alive or not is pretty hard to know. Usually, you can try to ping the server and if it doesn't respond within a set amount of time (1-15 seconds is probably a range we could tune), you can assume the server is down. However, it could also be a network connection on our end (not connected to WiFi on a laptop, on a Pegasus compute node, etc). 

We could try something like this:
```python
import socket
def server_alive(host, port=80):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    result = sock.connect_ex(('irc.myserver.net', 6667))
    return result == 0 # 0 is if there was no error and the server is live.
```

Code from [here](https://stackoverflow.com/questions/40108043/how-to-check-if-a-server-is-up-or-not-in-python)

**Comment by falkamelung** [comment]
closing and moving suggestion to dem_rsmas..py
