### ISSUE TITLE
date format in *template file: 2017-10-15 versus 20171015

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#136]
A frequent user error (at least mine) is that dates are specified in the wrong format because different packages require different formats. I did
```
ssaraopt.startDate  = 2017-10-15
pysar.network.startDate   = 2017-11-13
```
but it should be
```
ssaraopt.startDate  = 2017-10-15
pysar.network.startDate = 20171113
```
Very confusing! 

I like the ssara format as it is more readable. I will for now change `dataset_template` so that  `ssaraopt.startDate   = 20171015` works. This format is also required by ISCE. But it would be good to switch to pysar.network.startDate    = 2017-11-13`, or not? How do @mirzaees  and @yunjunz think?

**Comment by yunjunz** [comment]
I agree that YYYY-MM-DD format is more readable, but YYYYMMDD is more simple and easier to store, this is consistent with the `date` dataset stored in HDF5 file too; change to YYYY-MM-DD would  need pysar to make a fundamental change. So I would definitely vote for the YYYYMMDD format.

**Comment by falkamelung** [comment]
Following Yunjun's comment I am OK to change to YYYYMMDD for our ssara options

**Comment by Ovec8hkin** [comment]
We should use YYYYMMDD, as that can be stored as integer. But its important that we be consistent, so we should migrate ALL instances of dates to that format. This is the format we are using for the hazards website, and I believe its the format Im using in run_operations.py (could be wrong though).
