### ISSUE TITLE
process_rsmas.py does not update stack_sentinel_template.txt

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#145]
Here the updating issue.  I ran `process_rsmas.py /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/TangshanSenDT149.template --startmakerun`. The `$TE/*template file` contains `#sentinelStack.startDate`. The ` stackSentinel_template.txt` does not. It is younger but was not updated.

 ```
//login3/projects/scratch/insarlab/famelung/TangshanSenDT149[1018] !gre
grep sentinelStack.startDate TangshanSenDT149.template stackSentinel_template.txt 

TangshanSenDT149.template:  #sentinelStack.startDate             = 2016-05-13                                          # '1 2'                                           
stackSentinel_template.txt:  sentinelStack.startDate                   = 2016-05-13         # [YYYY-MM-DD]. auto for first date available

//login3/projects/scratch/insarlab/famelung/TangshanSenDT149[1019] ll sentinelStack.startDate TangshanSenDT149.template stackSentinel_template.txt
ls: cannot access sentinelStack.startDate: No such file or directory
-rw-rw--w-+ 1 famelung insarlab 2677 Apr 28 21:09 stackSentinel_template.txt
-rw-rw-r--+ 1 famelung insarlab 3901 Apr 28 19:13 TangshanSenDT149.template
```

**Comment by falkamelung** [comment]
So if I say `sentinelStack.startDate  = auto` the `stackSentinel_template.txt ` is updated (see below). So this issue occurs only if the `#` is place at the beginning of a line? I believe Josh's dataset_template.py can handle this. In any case, it would be good to support commenting out of a line.

```
//login4/projects/scratch/insarlab/famelung/TangshanSenDT149[1113] grep startDate stackSentinel_template.txt TangshanSenDT149.template 

stackSentinel_template.txt:sentinelStack.startDate                   = auto         # [YYYY-MM-DD]. auto for first date available
TangshanSenDT149.template:sentinelStack.startDate             = auto  # 2016-05-13                                          # '1 2'                                           
TangshanSenDT149.template:pysar.network.startDate             = auto                                              # [20090101 / no], auto for no                    

//login4/projects/scratch/insarlab/famelung/TangshanSenDT149[1114] ll stackSentinel_template.txt TangshanSenDT149.template 

-rw-rw--w-+ 1 famelung insarlab 2671 Apr 28 22:44 stackSentinel_template.txt
-rw-rw-r--+ 1 famelung insarlab 3908 Apr 28 21:54 TangshanSenDT149.template
```

**Comment by mirzaees** [comment]
I told Josh to add exception for ignoring these lines that are commented out long time ago, I think he fixed it but don't know why it is still not working.

**Comment by falkamelung** [comment]
I am looking at it. There is are two bugs (I think). One is that the `stackSentinel_template.txt` is not overwritten with the default file. @mirzaees  you know where in the code this is done? I did not find yet.

**Comment by mirzaees** [comment]
@falkamelung, in the 'create_or_update_template' function, following line is supposed to overwrite the default values based on custom template:
inps.template = Template(inps.custom_template_file).update_options(inps.template_file)

**Comment by falkamelung** [comment]
In [this line](https://github.com/geodesymiami/rsmas_insar/blob/edea2646662018a7617100c0ec4d4dbf4b62244a/rinsar/_processSteps.py#L290) it sends `inps.template_file` to the `dataset_template` function, which reads it from file [here](https://github.com/geodesymiami/rsmas_insar/blob/edea2646662018a7617100c0ec4d4dbf4b62244a/rinsar/dataset_template.py#L74).  So if `stackSentinel_template.txt` is already modified it takes the modification as default.  
We should either (1) give the default_template contents (not the default_template_file) to `dataset_template`, or (2) don't take existing `stackSentinel_template [here](https://github.com/geodesymiami/rsmas_insar/blob/edea2646662018a7617100c0ec4d4dbf4b62244a/rinsar/_process_utilities.py#L126) , or (3) create a virgin default template file in `dataset_template.update`. The second options seems to make most sense. So I should `create_default_template` so that ALWAYS a new default template id created?

**Comment by mirzaees** [comment]
yes I think that makes sense. No you don't need to always create_default_template.
If you like, you can look at the runfiles branch, I have already fixed these issues and the output for 
inps is clean and nice. also I removed all TemplateTuples.
