### ISSUE TITLE
shorten wait time of download_ssara_rsmas

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#15]
Once download_ssara is completed, it takes a while (I think 10 minutes) until it exits and the next step is done (which is download_asferial).
Can we reduce this waiting time?

**Comment by Ovec8hkin** [comment]
Do you want the time reduced only for the final wait? That will be significantly more difficult as it requires checking for the exact completion time, rather than a general one. I can easily reduce the waiting time across the board if that is what was intended. What time would you like?

**Comment by falkamelung** [comment]
Hi Josh,
Preferred would be no wait time (or, say, 30 sec)  just after the last download. But I don’t remember how complicated that is. You could check whether the number of of downloaded granules is correct (I know, we can’t check the size). If it is it exists without waiting.
Falk
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://yyy.rsmas.miami.edu/users/famelung/
InSAR data:
http://insarmaps.miami.edu

On Oct 9, 2018, at 1:56 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you want the time reduced only for the final wait? That will be significantly more difficult as it requires checking for the exact completion time, rather than a general one. I can easily reduce the waiting time across the board if that is what was intended. What time would you like?

**Comment by Ovec8hkin** [comment]
That might be more difficult to achieve than you would expect. Is the extra few minutes wait really that big a deal in the grand scheme of things that we need to remove or shorten it? Its definitely not a major contributor to the total runtime of the processing routine.

**Comment by falkamelung** [comment]
The main thing is that the unit test, which takes 30 minutes will be accelerated significantly. And then hopefully people will do it.

Shaving of 10 minutes from  4 hours processing is also not bad.
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://yyy.rsmas.miami.edu/users/famelung/
InSAR data:
http://insarmaps.miami.edu

On Oct 9, 2018, at 3:23 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


That might be more difficult to achieve than you would expect. Is the extra few minutes wait really that big a deal in the grand scheme of things that we need to remove or shorten it? Its definitely not a major contributor to the total runtime of the processing routine.

**Comment by Ovec8hkin** [comment]
To be fair, that is not a script that should be used for testing installations or unit testing, for exactly that reason (plus, shrinking the exit time isn't going to give you that much an increase in testing time). Second, a 4% speed increases is not much, especially considering the degree of difficulty in the implementation. I can universally shrink the wait time down some so we wait less time in total, but determining the exact termination time of the download and exiting is a lot more complicated and likely not worth the small speed increases you would see.

**Comment by falkamelung** [comment]
That is fine. Then let’s just do the universal shrinking of the wait time. When everything is working fine and we are really operational we can increase again. Just let me know where it is.
Falk
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://yyy.rsmas.miami.edu/users/famelung/
InSAR data:
http://insarmaps.miami.edu

On Oct 10, 2018, at 3:54 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


To be fair, that is not a script that should be used for testing installations or unit testing, for exactly that reason (plus, shrinking the exit time isn't going to give you that much an increase in testing time). Second, a 4% speed increases is not much, especially considering the degree of difficulty in the implementation. I can universally shrink the wait time down some so we wait less time in total, but determining the exact termination time of the download and exiting is a lot more complicated and likely not worth the small speed increases you would see.
