### ISSUE TITLE
Suggest final directory structure

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#158]
@2gotgrossman @Ovec8hkin @mirzaees @yunjunz 
I am considering one last change to our directory structure. We currently have a rather artificial separation between /sources and /3rdparty which should be one. And, isn’t it  weird to have the miniconda and accounts directories within rsmas_insar? Below the current structure and two suggestions. rsmas_insar uses ssara and pysar, So should they be inside rsmas_insar? Please let me know what you think.

CURRENT:
/rsmas_insar/rinsar/
/rsmas_insar/setup/
/rsmas_insar/setup/accounts
/rsmas_insar/3rdparty/miniconda3
/rsmas_insar/3rdparty/ssara
/rsmas_insar/3rdparty/pykml
/rsmas_insar/3rdparty/pyaps
/rsmas_insar/3rdparty/tippecanoe
/rsmas_insar/sources/pysar/

SUGGESTION1
/rsmas_insar/rinsar/
/rsmas_insar/setup/
/rsmas_insar/sources/ssara
/rsmas_insar/sources/pysar/
/rsmas_insar/sources/pykml
/rsmas_insar/sources/pyaps
/rsmas_insar/sources/tippecanoe
/miniconda3
/accounts

SUGGESTION2
/rsmas_insar/rinsar/
/rsmas_insar/setup/
/sources/ssara
/sources/pysar/
/sources/pykml
/sources/pyaps
/sources/tippecanoe
/miniconda3
/accounts

**Comment by mirzaees** [comment]
Hi @falkamelung 
if I want to choose from your suggestions, the second seems better. but I like the current structure because, all compiled directories are in 3rdparty and all modules and python scripts are in sources. only the `accounts` location is not right. which can be moved to sources

**Comment by falkamelung** [comment]
Thank you for your feedback. The accounts dir disturbs be most. Just moving this repo elsewhere would be easiest.  I though to have python within the repo is  weird as well. But maybe I should not worry?

I thought we should get rid of everything that gives some weird git status messages (see below) but maybe that is OK?

```
//vis2/nethome/famelung/test/test1/rsmas_insar/setup[1026] git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ../rinsar/execute_stacksentinel_run_files.py
	modified:   ../samples/unittestGalapagosSenDT128.template
	modified:   ../samples/unittestKrakatoaSenDT47.template
	modified:   install_credential_files.csh

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../3rdparty/
	../rinsar/qqdataset_template.py
	accounts/
	downloads/
	../sources/PySAR/
	../sources/geodmod/
	../sources/isceStack/
	../sources/rsmas_tools/
	../sources/ssara_ASF/password_config.py

```

**Comment by mirzaees** [comment]
python location is fine, all folders in 3rdparty are at the same level I think. 
these git messages are unavoidable. to solve them, we might have to separate some repositories and have multi repositories on github mainly separate rinsar which we don't want or have another parent folder other than rsmas_insar. I don't know how serious/bad is having these git messages to worth reorganizing. 
@2gotgrossman ?

**Comment by Ovec8hkin** [comment]
In general, its usually not advised to nest git repositories, or to commit/version control code that you don't own, or may be updated by a third-party later. In our case, I don't think we should be placing any of the `/3rdparty/` directory under version control. You can always add the required commands to install those 3rdparty scripts or modules to one of the setup files, but I don't think it's a good idea to continue to commit code we don't own, regardless of the directory structure.

@2gotgrossman thoughts?

**Comment by Ovec8hkin** [comment]
As to the matter of accounts, those should not be version controlled at all, as they are user specific. We should really stop including account specific information in these public repositories for privacy and security reasons completely.

**Comment by falkamelung** [comment]
Thank you for your feedback. Moved just the accounts repo out of rsmas_insar.
