### ISSUE TITLE
hazard product generation

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#168]
Hi Falk,

This is how you can save a interferogram file in to gdal .vrt format:

import isceobj
ifg = np.memmap(outputint_name , dtype=np.complex64, mode='w+', shape=(n_line, width))
Ifs[:,:] = interferogram_rasterfile
obj_int = isceobj.createIntImage()
obj_int.setFilename(outputint_name)
obj_int.setWidth(width)
obj_int.setLength(n_line)
obj_int.setAccessMode('READ')
obj_int.renderHdr()
obj_int.renderVRT()

This is in complex format but if you want to save in float:

IML.renderISCEXML(outpatient_name, 1, n_line, width, 'f', 'BIL')

out_img = isceobj.createImage()
out_img.load(outputint_name + '.xml')
out_img.imageType = 'f'
out_img.renderHdr()
cmd = 'gdal_translate -of ENVI -co INTERLEAVE=BIL ' + outputint_name + '.vrt ' + outputint_name
os.system(cmd)

If you want to add metadata to art files:

ds = gdal.Open(outputint_name, gdal.GA_ReadOnly)

ds.SetMetadata({'plmethod': inps.plmethod})

XXXXXXXXXX
Hi Falk,

You need to have merged/SLC products to be able to create geotiffs out of them.
If you call: export_ortho_geo.py   $TE/template,
It will first create a lat and a lon needed for georectified products that you can find in geom_master_noDEM folder.
Then creates 2 run list: run_amplitude_ortho and run_amplitude_geo. Which you can find in run_files folder
And then uses submit_run_jobs to execute them.
But the script that creates geotiff for each image is export_amplitude_tiff.py
The inputs are: the slc (date), bounding box, output type (Ortho, Geo).
And outputs are geo and ortho rectified backscatters (find them in GeoOrtho_tiff folder)

You better modify export_amplitude_tiff.py to accept coherence or interferogram instead of slc.
As long as all products share the same size (lines and samples), the metadata that is created here works for all.
For Coh and Int, you need to input your gdal product, follow the steps in export_amplitude_tiff.py to call geocodeGdal.py and then the array2raster function. 
Just do not run following lines for them:

array = np.abs(ds.GetRasterBand(1).ReadAsArray())
del ds

##
array = np.where(array > 0, 10.0 * np.log10(pow(array,2)) - 83.0, array)

Regards,
Sara

**Comment by falkamelung** [comment]
Hi @mirzaees,  It works reasonable well…, ...except the bug I slacked you about.  Three things:
1. It would be good if every major script records in the /projectName/log. I only see  very little (see below, it should not record in  /projectName/run_files/log)
2. We should think about coherent naming (geo is not so good as it stands in ISCE for fully geocoded).
3. Shall we use for everything all processing parameters as given in the template (looks, subset instead of bounding box)? 

e.g.
```
backscatter_ortho_20180213_.tif
backscatter_rect_20180213_.tif (or backscatter_20180213_.tif)
coherence_ortho_20180108_20180120.tif
coherence_20180108_20180120.tif
```

Here the log file:
```
//login4/projects/scratch/insarlab/famelung/unittestKrakatoaSenAT171[1145] cat log
20190512:210247 * ##### NEW RUN #####
20190512:210247 * process_rsmas.py /nethome/famelung/test/development/rsmas_insar/samples/unittestKrakatoaSenAT171.template
20190512:210257 * download_ssara_rsmas.py /nethome/famelung/test/development/rsmas_insar/samples/unittestKrakatoaSenAT171.template
20190512:210504 * download_asfserial_rsmas.py /nethome/famelung/test/development/rsmas_insar/samples/unittestKrakatoaSenAT171.template
//login4/projects/scratch/insarlab/famelung/unittestKrakatoaSenAT171[1146] cat run_files/log
20190513:045409 * ifgramStack_to_ifgram_and_coherence.py /nethome/famelung/test/development/rsmas_insar/samples/unittestKrakatoaSenAT171.template
```

Here the directory listing:
```
//login4/projects/scratch/insarlab/famelung/unittestKrakatoaSenDT47/run_files[1130] ll ../hazard_products/
total 964192
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 coherence_20180108_20180120.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 coherence_20180120_20180201.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 coherence_20180201_20180213.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 coherence_20180213_20180225.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 coherence_20180225_20180309.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 coherence_20180309_20180321.tif
-rw-rw--w-+ 1 famelung insarlab 125587343 May 13 06:50 Geo_20180213_backscatter.tif
-rw-rw--w-+ 1 famelung insarlab 125517323 May 13 06:50 Geo_20180225_backscatter.tif
-rw-rw--w-+ 1 famelung insarlab 125473773 May 13 06:50 Geo_20180309_backscatter.tif
-rw-rw--w-+ 1 famelung insarlab 125721189 May 13 06:49 Geo_20180321_backscatter.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 interferogram_20180108_20180120.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 interferogram_20180120_20180201.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 interferogram_20180201_20180213.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 interferogram_20180213_20180225.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 interferogram_20180225_20180309.tif
-rw-rw--w-+ 1 famelung insarlab   1346114 May 13 07:16 interferogram_20180309_20180321.tif
-rw-rw--w-+ 1 famelung insarlab  93033364 May 13 06:48 Ortho_20180108_backscatter.tif
-rw-rw--w-+ 1 famelung insarlab 125303990 May 13 06:48 Ortho_20180120_backscatter.tif
-rw-rw--w-+ 1 famelung insarlab 124926604 May 13 06:48 Ortho_20180225_backscatter.tif
-rw-rw--w-+ 1 famelung insarlab 125130105 May 13 06:47 Ortho_20180321_backscatter.tif
```

**Comment by mirzaees** [comment]
what I am going to do next few days:

1.  update template reading and assigning to inps based on the format: `inps.template` and `inps.template_file`

2.  error files handling and moving to folder

3. moving dask config to project dir

4.  rename create_batch.py to job_submission.py

5. fix metadata for ifgramStack_to_ifgram_and_coherence.py

6. add multilooking and subset to backscatter products

7. use dask for squeesar and adapt to the new structure

8. rename SentinelStack to TopsStack and switch to (topsStack and stripmapStack instead of sentinelStack)

9. remove email run and add as a function to pysar and insarmap

10. rename pysar to mintpy

11. naming convention could be `Orthorectified_*` and `Georectified_*` for hazard products. any idea?

12. add log to all steps

@falkamelung please add to the list if anything is missing

**Comment by falkamelung** [comment]
Looks good. We also should have a Workflow without hazard product generation?
Here a few more items:
 - revisit module names. Do we have ‘stack’ only in stack specific modules? If we have to import for the modeling code from something called stack that would not be good.
- Add example(s) to Wiki (unittest*)
- Think about available tools for documentation (look at dinoSAR, MintPy). We want to keep it minimal (a couple of pages). If you could decide and get started a bit I can continue. 

- Lets think heavily about the rinsar-->minsar switch. Now it is easy.
