### ISSUE TITLE
rinsar --> minsar name change?

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#171]
Given that we now have MintPy I suggest we make the switch before anybody gets used to rinsar  (and before we start creating the modeling modules).  minsar  would go well with MintPy. Is there  a tentative name for the squeesar code?

@yunjunz @mirzaees @2gotgrossman @Ovec8hkin , any thoughts?

**Comment by mirzaees** [comment]
how about:
MINIPy : MIami Non linear Inversion in Python
MASk: MiAmi Squeesar
MiSPy: Miami Squeesar in Python

@falkamelung

**Comment by yunjunz** [comment]
SqueeSAR is a patent trademark, I guess that's why this word is not mentioned in the literature besides TRE's own paper and products. A name without it would probably be better.

**Comment by mirzaees** [comment]
@yunjunz, you are right, I don't like `SqueeSAR` name either. 
please mention if you have any idea about naming.

MiNIPy : Miami Non linear Inversion in Python  
MiNoPy: Miami Non linear Inversion in Python  
MiaNIPy: Miami Non linear Inversion in Python   
MiNIP  : MIami Non linear Inversion Package     
MInTIn or MINTIN : Miami Insar Time series Inversion
?

**Comment by falkamelung** [comment]
All look good. Getting rid of the squeeze is fine with me. MiNLPy would also go. We can decide when we have a first draft of the paper.
