### ISSUE TITLE
run_operations -- creating directories/files if not exist

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#20]
It will be nice  if run_operation could generate all needed directories and files (including stored_dates) if they don't exist.  That would allow us to design a big, second unit test including all/most datasets.

I would remove the OPERATIONS directory and then run_operations would just work.

**Comment by Ovec8hkin** [comment]
I will do this tomorrow. Shouldn't be too hard.

**Comment by Ovec8hkin** [comment]
This is actually a bit more complex than I previously thought. I will have to go through each of the auxiliary scripts that run_operations depends on (generate_templates.py) and edit those files to create where necessary, before carefully considering when we can safely assume that the directory structure should already exist based on past calls.

**Comment by falkamelung** [comment]
done
