### ISSUE TITLE
How to avoid double entries into the log file?

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#209]
Another minor annoyance is that the  log file gets two entries for `execute_runfiles.py` if run with the `--submit` option. Same for `process_rsmas.py`. It should not write the second entry. Any idea how to avoid this?  I looked at it several times, but nothing easy occurred to me. 

Lets discuss when we meet.

```
20190806:185553 * execute_runfiles.py --submit --walltime 16:00 /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/UbinasSenDT127.template 1 16
20190806:190306 * execute_runfiles.py --walltime 16:00 /nethome/famelung/insarlab/infiles/famelung/TEMPLATES/UbinasSenDT127.template 1 16
```

**Comment by mirzaees** [comment]
This happened because when we submit the script as a job, it basically runs the script again. so to avoid it, I changed the logging message line to where the task actually begins (after submitting job) but in the logging message, there is no more `--submit` flag printed
