### ISSUE TITLE
Check whether DEM is complete before skipping DEM generation

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#222]
I think currently we only check for the existence of the DEM folder to decide whether to skip the DEM generation step.  If the DEM folder is empty or some files are missing the processing fails.

We should check for the existence of all dem* files that are needed for processing.

Where would the checking be implemented? In `dem_rsmas.py` or in `process_rsmas.py`? Currently it regenerates the DEM  is called by either of those.

Another question is what `demMethod` option is used. It should use what is given in *template file or the minsar default value. If called with an option `dem_rsmas.py templatefile --ssara` this should overwrite  the value give in the template.  Are we doing this?

**Comment by mirzaees** [comment]
There was no checking for DEM! I added now to dem_rsmas.py and it will check for the products not the folder.

I rewrote the flag options. if there is no flag, it will look for demMethod option, if it does not find demMethod as well, the default will be ssara.
