### ISSUE TITLE
Renaming  of rsmas_insar scripts and repo

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#236]
Hi @mirzaees, @yunjunz 
I see the following inconsistent naming which we should change.  Please make suggestions and let me know and whether anything else should be changed:

For sure:
download_rsmas.py --> download_data.py
dem_rsmas.py --> download_dem.py
export_ortho_geo.py --> ?? maybe: hazard_products.py, generate_hazard_producs.py,, 
generate_image_products.py, generate_amplitude_ifgram_coherence.py ?

upload_image_products.py --> ingest_image_products.py 

Maybe:
RSMASINSAR_HOME --> MINSAR_HOME (environment variable)
RSMAS_INSAR --> MinSAR  (repository name)
process_rsmas.py --> processApp.py

Maybe not?
process_rsmas.py --> minsarApp.py, insarApp.py, process.py, processApp.py  ?

Process step:
geocode --> image_products
mintpy --> timeseries (there was an email to Sara about this, I think)

**Comment by falkamelung** [comment]
MinSAR

**Comment by mirzaees** [comment]
geocode --> imageProducts .      Done
