### ISSUE TITLE
Future deployments: on ASF's hyp3,  opensarlab, NSF 

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#238]
Get system to work on ASF's hyp3 system: 
http://hyp3.asf.alaska.edu/about

If there are too many limitations lets try a Science Gateway on Jetstream:
https://www.xsede.org/ecosystem/science-gateways

**Comment by jhkennedy** [comment]
@falkamelung This should be possible to do without too much problem and I can help with it sometime this spring.
