### ISSUE TITLE
ssara_federated_query.py uses topsStack.boundingBox

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#242]
It uses it to generate a search polygon. This is not ideal. How make it work with `stripmapStack`? I see two options:

- We adjust the code that it uses either `topsStack.boundingBox` or -`stripmapStack.boundingBox`, whatever it finds.
- We could introduce a `ssaraopt.boundingBox` option. If it does not exist it will look for another boundingBox option.

Any suggestion? Let's discuss.

Another item to discuss is how to do seasonal downloads. We could introduce
```
ssaraopt.seasonalStartDate=0601
ssaraopt.seasonalEndDate=0930
```

**Comment by qyoung23** [comment]
Can I process a full scale of an image if deleting option topsStack.boundingBox?

**Comment by qyoung23** [comment]
Can I process full scale of an image if deleting option topsStack.boundingBox?
