### ISSUE TITLE
delta_lat   in download_data.py

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#243]
Is the default now defined at one place? Let's discuss.  Previously it was defined at multiple places with different defaults, which has caused troubles ( `download_ssara.py` and `download_asfserial.py`)

This parameter is key for painless download. I am thinking of introducing delta_long as well.

**Comment by mirzaees** [comment]
it is defined once at process_utilities.py, in 'add_download_data'.
you could add any similar option for download data scripts here
