### ISSUE TITLE
Why are we setting hosts equal to number of tasks?

### ISSUE THREAD

**Issue by AlexandrosAliKhan** [geodesymiami/rsmas_insar#306]
https://github.com/geodesymiami/rsmas_insar/blob/f1048977ca0ff1bc7778d2d4aebba9c1365f2393/minsar/job_submission.py#L109

**Comment by falkamelung** [comment]
This is how it is supposed to be. It ensures that all jobs are run on the same node. Which is not relevant as we request only one core. But once we request 15 cores this should stay to make sure that all cores are on the same node.
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web:http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu

On Feb 26, 2020, at 11:12 AM, Alexandros Ali Khan <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/geodesymiami/rsmas_insar/blob/f1048977ca0ff1bc7778d2d4aebba9c1365f2393/minsar/job_submission.py#L109<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeodesymiami%2Frsmas_insar%2Fblob%2Ff1048977ca0ff1bc7778d2d4aebba9c1365f2393%2Fminsar%2Fjob_submission.py%23L109&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C46245418a11742f788de08d7bad6bcf1%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637183303766636295&sdata=pEVai946K0p5Mtr5Q%2Bcl7hs6Oo%2Fojpl%2FKEhSO0q%2Fcag%3D&reserved=0>

**Comment by AlexandrosAliKhan** [comment]
I believe that span[hosts=1] does that. I think it means do it on one host. If we set hosts to a number greater than one, I am not sure how it will behave. From what I have read I think hosts is only used with one. The same can be achieved with span[ptiles=15] This means that give me 15 cores per node. So I think span[ptiles] is used when you are dealing with multiple hosts.

**Comment by mirzaees** [comment]
This was correct for stampede but not pegasus. fixed it
closing the issue ...
