### ISSUE TITLE
Parallel Option Not Parsing

### ISSUE THREAD

**Issue by AlexandrosAliKhan** [geodesymiami/rsmas_insar#308]
https://github.com/geodesymiami/rsmas_insar/blob/f1048977ca0ff1bc7778d2d4aebba9c1365f2393/minsar/utils/download_asfserial_rsmas.py#L93
Even though I followed the same procedure with seasonalStart and EndDates in process_utilities.py, download_asfserial_rsmas.py claims `AttributeError: 'Namespace' object has no attribute 'parallel'`. This is for allowing the user to add parallel as an option in the command line rather than in the template file. Kindly let me know if anyone has any ideas.

**Comment by Ovec8hkin** [comment]
Have you added parallel as an option to the argument parser object to look for?

**Comment by AlexandrosAliKhan** [comment]
Yes. The flag_parser.add_argument() right?
________________________________

**Comment by mirzaees** [comment]
@AlexandrosAliKhan,  Is this still an issue?
