### ISSUE TITLE
New job_submission.py does not work on LSF

### ISSUE THREAD

**Issue by AlexandrosAliKhan** [geodesymiami/rsmas_insar#310]
https://github.com/geodesymiami/rsmas_insar/blob/74d4dc822adf6b99e88b2c50bbbf39f8ea7bbd9b/minsar/job_submission.py#L539
The old job_submission.py in accounts/test/development still works for me.

`//login4/projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128[1135] ~/rsmas_insar/minsar/job_submission.py /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files/run_9_merge_burst_igram --memory 1500 --walltime 8:00 --queuename general --outdir /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files
20200308:225149 * job_submission.py /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files/run_9_merge_burst_igram --outdir /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files

Working on a LSF machine ...

Traceback (most recent call last):
  File "/nethome/axk1168/rsmas_insar/minsar/job_submission.py", line 557, in <module>
    walltime=PARAMS.wall, queue=PARAMS.queue)
  File "/nethome/axk1168/rsmas_insar/minsar/job_submission.py", line 338, in submit_batch_jobs
    memory=memory)
  File "/nethome/axk1168/rsmas_insar/minsar/job_submission.py", line 539, in get_memory_walltime
    num_threads = config[step_name]['num_threads']
  File "/nethome/axk1168/test/development/rsmas_insar/3rdparty/miniconda3/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'num_threads'`

**Comment by mirzaees** [comment]
Hi Alex, I checked your branch, it is on 'JOB_SUBMISSION_SCHEME' now not on master. which one did you work with that you got this error?

**Comment by AlexandrosAliKhan** [comment]
JOB_SUBMISSION_SCHEME, but I think the error should take place on master as well. Will check and let you know.

Regards,
________________________________

**Comment by AlexandrosAliKhan** [comment]
I checked. The error still takes place on master. Kindly let me know how to proceed.

**Comment by mirzaees** [comment]
I fixed this, so I am closing the issue
