### ISSUE TITLE
Issues to look at for Josh

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#311]
How to avoid rsync ssh issue to get data from website?
Hazards:  VM using 1 CPU?
environment.bash and platforms.bash: replace by Python script and global python variables?

**Comment by Ovec8hkin** [comment]
Global python variables are bad. Best to do this in a similar way that @yunjunz handles options in MintPy, with a config file.

**Comment by falkamelung** [comment]
Currently we use environment variables for everything and it works well. Once you looked at `/setup/environment.bash` and at `/accounts/platform_defaults.bash we should decide whether *.cfg files are worth it. My guess is that we should keep PATH, PYTHONPATH, etc as environment variables, but other variables are better dealt with in a *.cfg file.
Would we expect users to have their own *.cfg files? Probably not. So maybe we set defaults in a *cfg file but users can overwrite the default by an environment variable?  It is of low priority but a plan on this would be helpful.

Here more details: From environment.bash everything until [here](https://github.com/geodesymiami/rsmas_insar/blob/9fb901ff0d8397c1fd02bfe56e7b0049637b4bf9/setup/environment.bash#L64) could go into an /minsar/setup/minsar.cfg
