### ISSUE TITLE
job_submission.py no attribute 'get_number_of_bursts'

### ISSUE THREAD

**Issue by AlexandrosAliKhan** [geodesymiami/rsmas_insar#320]
job_submission.py /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files/run_9_merge_burst_igram --memory 4000 --walltime 8:00 --queuename general --outdir /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files
1-->1
-1 -0.6 -91.4 -90.86-->'-1 -0.6 -91.4 -90.86'
auto-->auto
None-->None
1-->1
-1 -0.6 -91.4 -90.86-->'-1 -0.6 -91.4 -90.86'
template file exists: /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/unittestGalapagosSenDT128.template, no updates
Traceback (most recent call last):
  File "./job_submission.py", line 607, in <module>
    PARAMS = parse_arguments(sys.argv[1::])
  File "./job_submission.py", line 81, in parse_arguments
    job_params.num_bursts = putils.get_number_of_bursts(job_params)
AttributeError: module 'minsar.utils.process_utilities' has no attribute 'get_number_of_bursts'

**Comment by falkamelung** [comment]
Not relevant anymore
