### ISSUE TITLE
job_submission.py KeyError: 'num_threads'

### ISSUE THREAD

**Issue by AlexandrosAliKhan** [geodesymiami/rsmas_insar#321]
job_submission3.py /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files/run_9_merge_burst_igram --walltime 8:00 --queuename parallel --outdir /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files
1-->1
-1 -0.6 -91.4 -90.86-->'-1 -0.6 -91.4 -90.86'
auto-->auto
None-->None
1-->1
-1 -0.6 -91.4 -90.86-->'-1 -0.6 -91.4 -90.86'
template file exists: /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/unittestGalapagosSenDT128.template, no updates
20200316:183426 * job_submission.py /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files/run_9_merge_burst_igram --outdir /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files

Working on a LSF machine ...

Traceback (most recent call last):
  File "./job_submission3.py", line 624, in <module>
    walltime=PARAMS.wall, queue=PARAMS.queue) #num_bursts=PARAMS.num_bursts)
  File "./job_submission3.py", line 346, in submit_batch_jobs
    memory=memory, num_bursts=num_bursts)
  File "./job_submission3.py", line 604, in get_memory_walltime
    num_threads = config[step_name]['num_threads']
  File "/nethome/axk1168/test/development/rsmas_insar/3rdparty/miniconda3/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'num_threads'

################################################################################

job_submission3.py /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files/run_9_merge_burst_igram --walltime 8:00 --queuename parallel --outdir /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files
1-->1
-1 -0.6 -91.4 -90.86-->'-1 -0.6 -91.4 -90.86'
auto-->auto
None-->None
1-->1
-1 -0.6 -91.4 -90.86-->'-1 -0.6 -91.4 -90.86'
template file exists: /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/unittestGalapagosSenDT128.template, no updates
20200316:183702 * job_submission.py /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files/run_9_merge_burst_igram --outdir /projects/scratch/insarlab/axk1168/unittestGalapagosSenDT128/run_files

Working on a LSF machine ...

Traceback (most recent call last):
  File "./job_submission3.py", line 624, in <module>
    walltime=PARAMS.wall, queue=PARAMS.queue) #num_bursts=PARAMS.num_bursts)
  File "./job_submission3.py", line 346, in submit_batch_jobs
    memory=memory, num_bursts=num_bursts)
  File "./job_submission3.py", line 606, in get_memory_walltime
    num_threads = config['DEFAULT']['num_threads']
  File "/nethome/axk1168/test/development/rsmas_insar/3rdparty/miniconda3/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'num_threads'

**Comment by mirzaees** [comment]
fixed
