### ISSUE TITLE
bash  job submission script

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#400]
A big item is in job_submit.bash to check before submitting how many jobs are already submitted. If more then 25 are submitted SLURM throws an error. So if 25 jobs are running/pending, submit_jobs.bash should wait 5 minutes and then try again. It should check again the number of running jobs and submit only if there is a slot open.

Alternatively, you could run `sbatch`, trap the exit code and wait if an error occurred.  After 5 minutes try again.

This is important. It will double the throughput as we can run more workflows simultaneously.

We then need `run_operations.bash`. It should do something similar but check for the numbers of workflow running using `scontrol`. We will have a variable MAX_NUMBER_OF_WORKFLOWS=4. If it is exceeded it would wait.  We would use the same function in `minsarApp.bash`

```
//login3/scratch/05861/tg851601/code/rsmas_insar/minsar[1129] scontrol show jobid -dd 6524057
JobId=6524057 JobName=run_09_fullBurst_geo2rdr_3
   UserId=tg851601(851601) GroupId=G-820134(820134) MCS_label=N/A
   Priority=490 Nice=0 Account=TG-EAR200012 QOS=normal
   JobState=PENDING Reason=Priority Dependency=(null)
   Requeue=0 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   DerivedExitCode=0:0
   RunTime=00:00:00 TimeLimit=02:57:00 TimeMin=N/A
   SubmitTime=2020-09-28T08:55:40 EligibleTime=2020-09-28T08:55:40
   AccrueTime=2020-09-28T08:55:40
   StartTime=Unknown EndTime=Unknown Deadline=N/A
   PreemptTime=None SuspendTime=None SecsPreSuspend=0
   LastSchedEval=2020-09-28T13:36:00
   Partition=skx-normal AllocNode:Sid=login3:313573
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=(null)
   NumNodes=1-1 NumCPUs=48 NumTasks=48 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=48,node=1,billing=48
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=1 MinMemoryNode=0 MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=NO Contiguous=0 Licenses=(null) Network=(null)
   Command=/scratch/05861/tg851601/WenchuanSenDT135/run_files/run_09_fullBurst_geo2rdr_3.job
   WorkDir=/scratch/05861/tg851601/WenchuanSenDT135
   StdErr=/scratch/05861/tg851601/WenchuanSenDT135/run_files/run_09_fullBurst_geo2rdr_3_%J.e
   StdIn=/dev/null
   StdOut=/scratch/05861/tg851601/WenchuanSenDT135/run_files/run_09_fullBurst_geo2rdr_3_%J.o
   Power= 
```
env | grep MAX
MAX_JOBS_PER_QUEUE=25

other items:
- **minsarApp.bash** 
Proper exit code of submit_bash (FA: need to test whether this is still a problem)
Currently stops after download with message
```
404 NOT FOUND
2020-09-19 07:01:01 ERROR 404: NOT FOUND.

404 NOT FOUND
2020-09-19 07:01:01 ERROR 404: NOT FOUND.

404 NOT FOUND
2020-09-19 07:01:01 ERROR 404: NOT FOUND.

Terminated
```
- get *.job files using a glob (as we have different *job files for different workflows)
`ls run_files/run_[0,1][0-9]_*.job smallbaseline_wrapper.job insarmaps.job `

- dummy function (commented out but working) replacing `sbatch` with `submit_command` function (to use sbatch for SLURM and bsub for LSF) using JOBSCHEDULER

- **Monitoring** 
How to readily monitor multiple jobs? Think of how we would implement in run_operations.bash (On stampede we likely would use `cron` ?
```
submit_jobs.bash > ~/process_logs/`basename $PWD`_`date +%F-%H`.log
```

**Comment by Ovec8hkin** [comment]
The logging things should be easy to implement (the date formatting might get interesting, but I'm sure people have code for that online somewhere already). 

The options are already implemented for the run files 1-16 as specified above. If you want that control for the other custom job files, the name you specify after the command line flag is going to need to match the name of the job file exactly (ie. we can't have `--start timeseries` run `smallbaseline_wrapper.job`; you would need to, instead, specify `--start smallbaseline_wrapper` or rename the job file to `timeseries.job`. 

I don't understand what the monitoring thing is about.

**Comment by Ovec8hkin** [comment]
**rerun.log** - complete

**Comment by Ovec8hkin** [comment]
**logging** - complete

**Comment by Ovec8hkin** [comment]
**options** - complete
