### ISSUE TITLE
mark successful runs:    need new   check_for_success function

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#41]
The stored_date.date file should get a new entry only if a run was successful. The last two weeks there was no successful run (reason unclear) but the stored_date looks at if it was successful

//login4/nethome/dwg11/insarlab/OPERATIONS[106] cat stored_date.date 
GalapagosSenDT128: 2018-10-29T11:50:12.000000
GalapagosSenAT106: 2018-10-28T00:26:31.000000
KilaueaSenD87: 2018-10-26T16:16:08.000000
KilaueaSenAT124: 2018-10-29T04:30:35.000000
AgungSenDT32: 2018-10-28T21:52:27.000000
AgungSenAT156: 2018-10-31T10:41:48.000000
LombokSenDT32: 2018-10-28T21:52:27.000000
LombokSenAT156: 2018-10-31T10:41:48.000000
CotopaxiSenAT120: 2018-10-22T23:28:42.000000
ChilesSenAT120: 2018-10-22T23:28:42.000000
GalerasSenAT120: 2018-10-22T23:28:42.000000

**Comment by Ovec8hkin** [comment]
This is an easy fix.
