### ISSUE TITLE
RSMAS Style guide

### ISSUE THREAD

**Issue by gravelcycles** [geodesymiami/rsmas_insar#42]
This is a great place to discuss anything style-guide related. If you have any comments or questions on the current style guidelines, pop a question!

**Comment by falkamelung** [comment]
I see an '_' at the beginning of the function name in process_sentinel. Is this something to do for particular mundane utility functions?

And this function requires a list as argument. How to indicate this in the function definition?

def _remove_directories(directories_to_delete):

**Comment by gravelcycles** [comment]
> I see an '_' at the beginning of the function name in process_sentinel. Is this something to do for particular mundane utility functions?
> 
> And this function requires a list as argument. How to indicate this in the function definition?
> 
> def _remove_directories(directories_to_delete):

Great question. Double underscores usually refer to "private" functions or variables in Python. These are variables and functions that should not be accessed from outside of the module you are writing. 

This is often a useful feature as you can be certain that you are only writing a function for yourself and no one one else will (should) use it. Therefore, you can modify and delete it as you'd like. This is called encapsulation.

However, the single underscore isn't widely used. Probably something that should be refactored.

More on "private" variables in Python [here](https://stackoverflow.com/questions/3385317/private-variables-and-methods-in-python)

**Comment by falkamelung** [comment]
Yunjun said that this could be used for functions which are meant to be local. Not sure what exactly that means, but a useful convention would be to use it for functions which are not meant to be imported into anything else. This would go a long way in better organizing the functions. I found the blurb below on the web, saying the same thing.

_foo: this is just a convention, a way for the programmer to indicate that the variable is private (whatever that means in Python).

**Comment by gravelcycles** [comment]
I think Yunjun and I are talking about the same thing. The only change I would make though is to use [double underscores](https://stackoverflow.com/questions/6930144/underscore-vs-double-underscore-with-variables-and-methods)
