### ISSUE TITLE
ssara_federated_query.bash:  timeout slow wget processes  and 123 exit code

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#426]
1. Sometime wget processes become very slow (a factor of 100 slower than normal). Can we run the `wget` process with a timeout option?  The following works. `timeout 400` would be reasonable to check 

```
timeout 120 wget --continue --user famelung --password FalkAmelung1 https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20190716T135134_20190716T135201_028143_032DC3_F6AB.zip
```

I see two possibilities:
(1) Capture the exit_code and rerun wget process. 
(2) Go through the end and if just one wget process timed out rerun everything (repeat 5 times).  We may want to eliminate the `ssara_federated_query.py` call when rerunning, We could have `ssara_federated_query.bash --no_listing` to skip the listing option.

I like the second option.

2. Occasionally the `xargs wget` process exits with exit code 123.  I don't know why. Error does not seem reproducible. We should run again if this exit code is detected.

**Comment by Ovec8hkin** [comment]
Is it enough to simply redo the `wget` call? Something like this:

```bash
echo $urls | xargs -n 1 -P $parallel wget --continue --user $user --password $passwd
exit_code=$?
echo "Exit code from wget commands: $exit_code"

if [[ $exit_code -eq 123 ]]; then
    echo $urls | xargs -n 1 -P $parallel wget --continue --user $user --password $passwd
fi
```

**Comment by falkamelung** [comment]
Yes. We could have initially 3 redos. If we then have still exit_code 123 then wait 3 hours and try again. If after a total of 24 hours we still have 123 then exit.

**Comment by Ovec8hkin** [comment]
I implemented the above. Try it out. I managed to get it to exit with 123 status code, and It never repeated consecutively. I imagine that its caused by some type of network loss during the wget command, but that is just conjecture.
