### ISSUE TITLE
useful run_operations options 

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#43]
preferred:
run_operations.py --googlesheet https://docs.google.com/spreadsheets/d/1ILNfg9jJsebxSQUZF2ULCBgAnDJ41NRc1X8j6xsZUUI/edit#gid=1436095665

else
run_operations.py --googlesheet 1ILNfg9jJsebxSQUZF2ULCBgAnDJ41NRc1X8j6xsZUUI

**Comment by Ovec8hkin** [comment]
What is this option supposed to do?
