### ISSUE TITLE
Deleting Zero-Line Error Files

### ISSUE THREAD

**Issue by gravelcycles** [geodesymiami/rsmas_insar#44]
In the function `check_error_files_sentinelstack` in `_process_utilities.py`, error files with Zero Size and error files with Zero (new) Lines are deleted. Why do we need to delete files with Zero Lines?

I'm looking to either refactor out that function or remove its use of `subprocess`.

Also, I would that this currently deletes files with zero _**new**_ lines. `wc -l` scans for the newline character. 

@falkamelung and @Ovec8hkin, any thoughts?

https://github.com/geodesymiami/rsmas_isce/blob/806e361050a1ebd6ccc54c9361fdd34e817bbc4a/_process_utilities.py#L503

**Comment by gravelcycles** [comment]
Also, `check_error_files_sentinelstack` is not used at all. It is only imported by `process_sentinel.py`. What's the status of this function?

**Comment by falkamelung** [comment]
The processing system produces empty error files as well as error files that have zero lines (which is a bug we have no control of). This makes it difficult to detect real errors.

Will create this later today, unless you have time for that

ls -l /projects/scratch/insarlab/famelung/GalapagosSenDT128/run_files/


total 10144
-rw-rw--w-+ 1 famelung insarlab 300355 Nov  6 07:14 isce.log
-rw-rw--w-+ 1 famelung insarlab   2480 Nov  6 06:49 run_10_filter_coherence
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_10_18173756.e
-rw-rw--w-+ 1 famelung insarlab   5063 Nov  6 07:14 run_10_filter_coherence_10_18173756.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_10.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_11_18173757.e
-rw-rw--w-+ 1 famelung insarlab   5063 Nov  6 07:14 run_10_filter_coherence_11_18173757.o
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_1_18173747.e
-rw-rw--w-+ 1 famelung insarlab   5054 Nov  6 07:14 run_10_filter_coherence_1_18173747.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_11.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_12_18173758.e
-rw-rw--w-+ 1 famelung insarlab   5060 Nov  6 07:14 run_10_filter_coherence_12_18173758.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_12.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_13_18173759.e
-rw-rw--w-+ 1 famelung insarlab   5060 Nov  6 07:14 run_10_filter_coherence_13_18173759.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_13.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_14_18173760.e
-rw-rw--w-+ 1 famelung insarlab   5060 Nov  6 07:14 run_10_filter_coherence_14_18173760.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_14.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_15_18173761.e
-rw-rw--w-+ 1 famelung insarlab   5060 Nov  6 07:14 run_10_filter_coherence_15_18173761.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_15.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_16_18173762.e
-rw-rw--w-+ 1 famelung insarlab   5060 Nov  6 07:14 run_10_filter_coherence_16_18173762.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_16.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_17_18173763.e
-rw-rw--w-+ 1 famelung insarlab   5060 Nov  6 07:14 run_10_filter_coherence_17_18173763.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_17.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_18_18173764.e
-rw-rw--w-+ 1 famelung insarlab   5060 Nov  6 07:14 run_10_filter_coherence_18_18173764.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_18.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_19_18173765.e
-rw-rw--w-+ 1 famelung insarlab   5060 Nov  6 07:14 run_10_filter_coherence_19_18173765.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_19.job
-rw-rw--w-+ 1 famelung insarlab    435 Nov  6 07:14 run_10_filter_coherence_1.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_20_18173766.e
-rw-rw--w-+ 1 famelung insarlab   5060 Nov  6 07:14 run_10_filter_coherence_20_18173766.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_10_filter_coherence_20.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_2_18173748.e
-rw-rw--w-+ 1 famelung insarlab   5054 Nov  6 07:14 run_10_filter_coherence_2_18173748.o
-rw-rw--w-+ 1 famelung insarlab    435 Nov  6 07:14 run_10_filter_coherence_2.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_3_18173749.e
-rw-rw--w-+ 1 famelung insarlab   5054 Nov  6 07:14 run_10_filter_coherence_3_18173749.o
-rw-rw--w-+ 1 famelung insarlab    435 Nov  6 07:14 run_10_filter_coherence_3.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_4_18173750.e
-rw-rw--w-+ 1 famelung insarlab   5054 Nov  6 07:14 run_10_filter_coherence_4_18173750.o
-rw-rw--w-+ 1 famelung insarlab    435 Nov  6 07:14 run_10_filter_coherence_4.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_5_18173751.e
-rw-rw--w-+ 1 famelung insarlab   5057 Nov  6 07:14 run_10_filter_coherence_5_18173751.o
-rw-rw--w-+ 1 famelung insarlab    435 Nov  6 07:14 run_10_filter_coherence_5.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_6_18173752.e
-rw-rw--w-+ 1 famelung insarlab   5057 Nov  6 07:14 run_10_filter_coherence_6_18173752.o
-rw-rw--w-+ 1 famelung insarlab    435 Nov  6 07:14 run_10_filter_coherence_6.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_7_18173753.e
-rw-rw--w-+ 1 famelung insarlab   5057 Nov  6 07:14 run_10_filter_coherence_7_18173753.o
-rw-rw--w-+ 1 famelung insarlab    435 Nov  6 07:14 run_10_filter_coherence_7.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_8_18173754.e
-rw-rw--w-+ 1 famelung insarlab   5057 Nov  6 07:14 run_10_filter_coherence_8_18173754.o
-rw-rw--w-+ 1 famelung insarlab    435 Nov  6 07:14 run_10_filter_coherence_8.job
-rw-rw--w-+ 1 famelung insarlab  13608 Nov  6 07:14 run_10_filter_coherence_9_18173755.e
-rw-rw--w-+ 1 famelung insarlab   5057 Nov  6 07:14 run_10_filter_coherence_9_18173755.o
-rw-rw--w-+ 1 famelung insarlab    435 Nov  6 07:14 run_10_filter_coherence_9.job
-rw-rw--w-+ 1 famelung insarlab   1360 Nov  6 06:49 run_11_merge_master_slave_slc
-rw-rw--w-+ 1 famelung insarlab      0 Nov  6 07:14 run_11_merge_master_slave_slc_10_18173776.e
-rw-rw--w-+ 1 famelung insarlab   2568 Nov  6 07:14 run_11_merge_master_slave_slc_10_18173776.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_11_merge_master_slave_slc_10.job
-rw-rw--w-+ 1 famelung insarlab      0 Nov  6 07:14 run_11_merge_master_slave_slc_11_18173777.e
-rw-rw--w-+ 1 famelung insarlab   2568 Nov  6 07:14 run_11_merge_master_slave_slc_11_18173777.o
-rw-rw--w-+ 1 famelung insarlab      0 Nov  6 07:14 run_11_merge_master_slave_slc_1_18173767.e
-rw-rw--w-+ 1 famelung insarlab   2797 Nov  6 07:14 run_11_merge_master_slave_slc_1_18173767.o
-rw-rw--w-+ 1 famelung insarlab    438 Nov  6 07:14 run_11_merge_master_slave_slc_11.job
-rw-rw--w-+ 1 famelung insarlab      0 Nov  6 07:14 run_11_merge_master_slave_slc_12_18173778.e
-rw-rw--w-+ 1 famelung insarlab   2848 Nov  6 07:14 run_11_merge_master_slave_slc_12_18173778.o

**Comment by gravelcycles** [comment]
Hmm, so which are the non-empty but zero-line error files you are referring to in the example you gave?

**Comment by falkamelung** [comment]
It is very easy to write. Don’t worry about it. You can correct later

Sent from my IPhone.

On Nov 6, 2018, at 10:52 AM, David W Grossman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, so which are the non-empty but zero-line error files you are referring to in the example you gave?

**Comment by Ovec8hkin** [comment]
Its not worth it to write it poorly now and correct it later. We need to get in the business of writing things correctly up front. And I wouldn't necessarily agree that that is easy. Seems like a lot of special cases that need very specific handling protocols.

**Comment by falkamelung** [comment]
done. It was very easy.

##########################################################################

def remove_zero_size_or_length_files(directory):
    """Removes files with zero size or zero length (*.e files in run_files)."""
    error_files  = glob.glob(directory + '/*.e')
    for item in error_files:
        if os.path.getsize(item) == 0:       # remove zero-size files
            os.remove(item)
        elif file_len(item) == 0:
            os.remove(item)                  # remove zero-line files
