### ISSUE TITLE
Acceleration of ssara_federated_query.bash

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#464]
Our download script is not optimal. It waits until all 5 granules are downloaded before it starts downloading the next five granules. Given that download speed varies widely between granules (any idea why this happens?). The time stamps of the example below show that it took 3-4 minutes to download the last granule.  During this time it could have downloaded several granules at regular speed. By always running 5 `wget` jobs simultaneously we could halfen the total download time.

```
-rw-rw---- 1 tg851601 4545167488 Feb 19 22:19 S1A_IW_SLC__1SDV_20210210T014205_20210210T014233_036521_0449DE_5901.zip
-rw-rw---- 1 tg851601 4047085215 Feb 19 22:21 S1A_IW_SLC__1SDV_20210210T014140_20210210T014207_036521_0449DE_4864.zip
-rw-rw---- 1 tg851601     423526 Apr 12 15:08 ssara_search_20210412200834.kml
-rw-rw---- 1 tg851601     104301 Apr 12 15:08 ssara_listing.txt
-rw-rw---- 1 tg851601       2649 Apr 12 22:16 log
-rw-rw---- 1 tg851601 3053691493 Apr 12 22:35 S1A_IW_SLC__1SDV_20210306T014204_20210306T014232_036871_045609_2232.zip
-rw-rw---- 1 tg851601 3809361181 Apr 12 22:35 S1A_IW_SLC__1SDV_20210222T014204_20210222T014232_036696_044FFD_06C1.zip
-rw-rw---- 1 tg851601 3644743269 Apr 12 22:35 S1A_IW_SLC__1SDV_20210306T014230_20210306T014257_036871_045609_D7B5.zip
-rw-rw---- 1 tg851601  874201701 Apr 12 22:35 S1A_IW_SLC__1SDV_20210306T014139_20210306T014206_036871_045609_4D84.zip
-rw-rw---- 1 tg851601 2675595877 Apr 12 22:35 S1A_IW_SLC__1SDV_20210222T014230_20210222T014257_036696_044FFD_C39C.zip
//login3/scratch/05861/tg851601/BalotschistanSenDT49/SLC[1112] lst
--rw-rw---- 1 tg851601 4550223128 Mar  2 18:35 S1A_IW_SLC__1SDV_20210222T014204_20210222T014232_036696_044FFD_06C1.zip
-rw-rw---- 1 tg851601 4082317219 Mar  2 18:40 S1A_IW_SLC__1SDV_20210222T014230_20210222T014257_036696_044FFD_C39C.zip
-rw-rw---- 1 tg851601 4019744642 Mar  8 13:48 S1A_IW_SLC__1SDV_20210306T014230_20210306T014257_036871_045609_D7B5.zip
-rw-rw---- 1 tg851601     423526 Apr 12 15:08 ssara_search_20210412200834.kml
-rw-rw---- 1 tg851601     104301 Apr 12 15:08 ssara_listing.txt
-rw-rw---- 1 tg851601       2649 Apr 12 22:16 log
-rw-rw---- 1 tg851601 4509278821 Apr 12 22:36 S1A_IW_SLC__1SDV_20210306T014204_20210306T014232_036871_045609_2232.zip
-rw-rw---- 1 tg851601 1717863013 Apr 12 22:36 S1A_IW_SLC__1SDV_20210306T014139_20210306T014206_036871_045609_4D84.zip
//login3/scratch/05861/tg851601/BalotschistanSenDT49/SLC[1116] lst
S1A_IW_SLC__1SDV_20210306T014230_20210306T014257_036871_045609_D7B5.zip
-rw-rw---- 1 tg851601     423526 Apr 12 15:08 ssara_search_20210412200834.kml
-rw-rw---- 1 tg851601     104301 Apr 12 15:08 ssara_listing.txt
-rw-rw---- 1 tg851601       2649 Apr 12 22:16 log
-rw-rw---- 1 tg851601 2162868837 Apr 12 22:37 S1A_IW_SLC__1SDV_20210306T014139_20210306T014206_036871_045609_4D84.zip
//login3/scratch/05861/tg851601/BalotschistanSenDT49/SLC[1117] lst
S1A_IW_SLC__1SDV_20210306T014230_20210306T014257_036871_045609_D7B5.zip
-rw-rw---- 1 tg851601     423526 Apr 12 15:08 ssara_search_20210412200834.kml
-rw-rw---- 1 tg851601     104301 Apr 12 15:08 ssara_listing.txt
-rw-rw---- 1 tg851601       2649 Apr 12 22:16 log
-rw-rw---- 1 tg851601 2893890149 Apr 12 22:40 S1A_IW_SLC__1SDV_20210306T014139_20210306T014206_036871_045609_4D84.zip
```

So we could either have 5 `xargs` processes running simultaneously, or we do some magic with loops.   In any case, it would be good to write the time of each `wget` download process into a logfile (`download_times.log`, create  `download_times.log.1`, `download_times.log.2`m etx, if file already exists).This will help to understand whether individaul granules are a particular problem.

**Comment by Ovec8hkin** [comment]
I have to look at how to do this exactly. While it sounds easy, `wget` has relatively poor support for parallel processes even using `xargs`. What I might have to do is collect process IDs from each wget process, then monitor those processes, and start up new processes as they finish using some fancy looping constructs.

**Comment by falkamelung** [comment]
You may want to look into the ssara_*py code. It is always downloading the specified granules in parallel.

**Comment by Ovec8hkin** [comment]
Doing it in python is lot different because of how python handles http requests. Theres a lot of wrapper code that goes into making the ssara*.py code run in parallel that is difficult to replace in pure bash.

**Comment by falkamelung** [comment]
I see.   Googling it this link shows some options, but you probably have found this already:
https://www.baeldung.com/linux/wget-parallel-downloading

**Comment by Ovec8hkin** [comment]
Whats the appropriate set of `ssara_federated_query.py` command line arguments for KilaueaSenAT124 and unittestGalapagosSenDT124

**Comment by falkamelung** [comment]
For `KilaueaSenAT124` it is 
```
ssara_federated_query.bash --platform=SENTINEL-1A,SENTINEL-1B --relativeOrbit=124 --intersectsWith='Polygon((-155.80 19.00, -155.80 20.00, -154.50 20.00, -154.50 19.00, -155.80 19.00))' --start=2018-09-01 --parallel=5 --print --download
```
For `GalapagosSenDT128`:
cat ssara_command.txt 
```
ssara_federated_query.bash --platform=SENTINEL-1A,SENTINEL-1B --relativeOrbit=128 --intersectsWith='Polygon((-91.40 -1.00, -91.40 -0.60, -90.86 -0.60, -90.86 -1.00, -91.40 -1.00))' --start=2016-06-01 --end=2016-12-31 --parallel=5 --print --download
```

**Comment by falkamelung** [comment]
@Ovec8hkin 
By the way: ssara_federated_query.bash could use another fix.  Look at the logging line below startring with `Running (with`s inserted)`. The `intersectsWith=` option does not have the quotes (`'`') that are required to run `ssara_federated_query.py`.  I added this logging but could not figure out how to add this daarn quote in bash. If you have a solution to this that would be great.




```
 ssara_federated_query.bash --platform=SENTINEL-1A,SENTINEL-1B --relativeOrbit=128 --intersectsWith='Polygon((-91.40 -1.00, -91.40 -0.60, -90.86 -0.60, -90.86 -1.00, -91.40 -1.00))' --start=2016-06-01 --end=2016-12-31 --parallel=5 --print --download
element 0: --platform=SENTINEL-1A,SENTINEL-1B
element 1: --relativeOrbit=128
element 2: --intersectsWith='Polygon((-91.40 -1.00, -91.40 -0.60, -90.86 -0.60, -90.86 -1.00, -91.40 -1.00))'
element 3: --start=2016-06-01
element 4: --end=2016-12-31
element 5: --parallel=5
element 6: --print
element 7: --download
parallel=5
--platform=SENTINEL-1A,SENTINEL-1B
Running (with`s inserted) ... ssara_federated_query.py --platform=SENTINEL-1A,SENTINEL-1B --relativeOrbit=128 --intersectsWith=Polygon((-91.40 -1.00, -91.40 -0.60, -90.86 -0.60, -90.86 -1.00, -91.40 -1.00)) --start=2016-06-01 --end=2016-12-31 --parallel=5 --print --maxResults=20000 > ssara_listing.txt
Datafiles to download: 17
URLs to download: https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SSV_20160605T114943_20160605T115018_011575_011AEF_98EA.zip https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SSV_20160629T114944_20160629T115019_011925_0125EE_41E2.zip https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SSV_20160711T114945_20160711T115020_012100_012BB7_AD1C.zip https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SSV_20160723T114945_20160723T115021_012275_01315B_4BF1.zip https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SSV_20160804T114946_20160804T115022_012450_01372F_C4E2.zip
^CFinished downloading files 5/17 succesfully.
```
It should write to screen:
```
Running ... ssara_federated_query.py --platform=SENTINEL-1A,SENTINEL-1B --relativeOrbit=128 --intersectsWith='Polygon((-91.40 -1.00, -91.40 -0.60, -90.86 -0.60, -90.86 -1.00, -91.40 -1.00))' --start=2016-06-01 --end=2016-12-31 --parallel=5 --print --maxResults=20000 > ssara_listing.txt
```

**Comment by Ovec8hkin** [comment]
> I see. Googling it this link shows some options, but you probably have found this already:
> https://www.baeldung.com/linux/wget-parallel-downloading

From what I can tell, the `xargs` suggestions from this looks works as intended, with one problem. Using this, we cant identify if a specific download process failed somewhere. For example, if there are 80 files to download, and download 43 fails, we cant positively identify it as download #43 and just restart that download, we would have to rerun the process for all files. Obviously this is sub optimal. I know using `wget --continue` will continue a file download that did not finish entirely, but Im not sure if this perfectly solves the problem.

I am going to make a new script `ssara_federated_query_new.bash` that implements the above for you to test. If it appears to work as intended, we can make it the official one.

**Comment by Ovec8hkin** [comment]
I just pushed an updated copy using the strategy from the link above. It is in `ssara_federated_query.bash`. The previous iteration that uses url batches is in `ssara_federated_query_old.bash`.
`

**Comment by falkamelung** [comment]
Just saw the previous message.  It would be great if we could write something about every downloaded file into a logfile, so that we can see how long it took, etc. Possibly listing the number of downloaded bytes.

Maybe add a tee/pipe into a file?

**Comment by Ovec8hkin** [comment]
Cant do this easily with xargs I don't think. You can try, but once you start using xargs for parallel processing, you lose the ability to work at the level of individual processes most of the time.

**Comment by falkamelung** [comment]
I think this is solved
