### ISSUE TITLE
—rapid option for submit_jobs.bash  plus parameter summary

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#476]
- Currently submit_jobs.bash sleeps 60 seconds and 300 seconds (5 min) before checking the state of a job (using sacct) and before trying to submit a new job when the `MAX_JOB_LINITS_PER QUEUE` (1, 25 for skx-dev, skx-normal) is reached, respectively. This work fine most of the time, but when running a small test workflow on skx-dev it will be better to have short wait times (20 seconds and 60 seconds, respectively). Can we swicth from hard-wired numbers to variables? The defaults would be 60,300 but an `—rapid` option would set to 20,60 ((`submit_jobs.bash $PWD —start 7 —rapid` )

- currently it is a bit messy which are the parameters of submit_jobs.bash and where they are set (I have seen different tasks limit of (3000) and skx-normal (1000 or 1500), I think). Could you add some explanation on this? A possible location is the —help message. Also please explain in the script where the parameters are defined. in the `queues.cfg` and overwritten if an environment variable is declared? I forgot what we decided to do. I admit that I said many times 'use en environment variable'.

**Comment by Ovec8hkin** [comment]
> * Currently submit_jobs.bash sleeps 60 seconds and 300 seconds (5 min) before checking the state of a job (using sacct) and before trying to submit a new job when the `MAX_JOB_LINITS_PER QUEUE` (1, 25 for skx-dev, skx-normal) is reached, respectively. This work fine most of the time, but when running a small test workflow on skx-dev it will be better to have short wait times (20 seconds and 60 seconds, respectively). Can we swicth from hard-wired numbers to variables? The defaults would be 60,300 but an `—rapid` option would set to 20,60 ((`submit_jobs.bash $PWD —start 7 —rapid` )
> *

Just pushed this. 

> * currently it is a bit messy which are the parameters of submit_jobs.bash and where they are set (I have seen different tasks limit of (3000) and skx-normal (1000 or 1500), I think). Could you add some explanation on this? A possible location is the —help message. Also please explain in the script where the parameters are defined. in the `queues.cfg` and overwritten if an environment variable is declared? I forgot what we decided to do. I admit that I said many times 'use en environment variable'.

Not sure what you're referring too here.
