### ISSUE TITLE
run_workflow.bash

### ISSUE THREAD

**Issue by mirzaees** [geodesymiami/rsmas_insar#499]
Hi @Ovec8hkin 

There is also a problem with run_workflow I am hoping you have a quick solution.
Following part of the code does not work properly:

https://github.com/geodesymiami/rsmas_insar/blob/d2a628fa28fbf820b276c9ca4d945c50c7474a1f/minsar/run_workflow.bash#L82-L130

To clarify, run_workflow accepts multiple input arguments but this part only checks for the first argument given. So if I run it like this:
`run_workflow.bash $template --start 1 --stop 8 --temp`

it will only check the `start` value not the rest.

Could you please take a look at this?

**Comment by falkamelung** [comment]
I think it works. Below some examples where I just  echo $tmp.  @mirzaees , In your example above you say `temp` ???

```
run_workflow.bash /scratch/05861/tg851601/MaunaLoaCskAT10 --dostep ifgrams --tmp
TMP true
/run_workflow.bash /scratch/05861/tg851601/MaunaLoaCskAT10 --start 7  --tmp
TMP true
run_workflow.bash /scratch/05861/tg851601/MaunaLoaCskAT10 --start 7  
TMP false
run_workflow.bash /scratch/05861/tg851601/MaunaLoaCskAT10 --start  7 --stop 9 --tmp
TMP true
```

**Comment by falkamelung** [comment]
Closing because I think it works
