### ISSUE TITLE
download_asfserial_rsmas and download_ssara_rsmas should run in any directory

### ISSUE THREAD

**Issue by Ovec8hkin** [geodesymiami/rsmas_insar#5]
Presently, `download_asfserial_rsmas.py` and `download_ssara_rsmas.py` download files to the current working directory. This is fine in general, but it requires that the the command is always run from the proper directory at the start. It is desirable to have these functions download data in the correct directory regardless of the location from which they are run. 

This is easily accomplishable by programmatically changing the current working directory to `$SCRATCHDIR/dataset_name/SLC` before downloading any data.

**Comment by falkamelung** [comment]
Falk did it
