### ISSUE TITLE
Is  MinSAR can be customized for Slurm server 

### ISSUE THREAD

**Issue by mohseniaref** [geodesymiami/rsmas_insar#528]
Hi,

I hope my message finds you well
I was wondering if MinSAR can be customized for a Slurm server ? It would be great if it is possible to install it in our University server

Best regards,
Mohammad

**Comment by falkamelung** [comment]
Yes, it works for Slurm. We are using it on Stampede2@TACC. There is likely some inadvertent code for this platform built in.
