### ISSUE TITLE
Execution of unknown scripts: `stackSentinel.py` and `stackSentinel_squeesar.py`

### ISSUE THREAD

**Issue by gravelcycles** [geodesymiami/rsmas_insar#65]
In `create_stacksentinel_run_files.py`, there is a `subprocess.Popen` command to `stackSentinel.py` and `stackSentinel_squeesar.py`. However, those two scripts don't exist in the `rsmas_isce` directory.

[Here are the relevant lines](https://github.com/geodesymiami/rsmas_isce/blob/b0b62058d2ceab1a7ee386ba0844dce35ec6bce5/create_stacksentinel_run_files.py#L70-L109)

@mirzaees , this script is called in _processSteps.py, so I thought you might have some context on it.

**Comment by gravelcycles** [comment]
```python
script = 'stackSentinel.py'
    extraOptions = ''
    if inps.processingMethod == 'squeesar' or inps.processingMethod == 'ps':
        script = 'stackSentinel_squeesar.py'
        extraOptions = ' --processingmethod ' + inps.processingMethod

....
   
    command = script + extraOptions

....

    command = '('+command+' | tee '+out_file+'.o) 3>&1 1>&2 2>&3 | tee '+out_file+'.e'

....

    status = subprocess.Popen( command, shell=True).wait()
```

**Comment by mirzaees** [comment]
I am working on this part, it will be changed soon

**Comment by gravelcycles** [comment]
Hi @mirzaees, any update on this?

**Comment by mirzaees** [comment]
Hi @2gotgrossman , just commited.
Those scripts (stackSentinel.py, stackSentinel_squeesar.py) are called from other directories

**Comment by Ovec8hkin** [comment]
Is this resolved? Can I close it?

**Comment by mirzaees** [comment]
> Is this resolved? Can I close it?

yes it is
