### ISSUE TITLE
files2 not used 

### ISSUE THREAD

**Issue by lily-wittle** [geodesymiami/rsmas_insar#66]
Try block seems unnecessarily complicated since files2 is never used - I believe those 4 lines could be replaced with
```dem_file = glob.glob(inps.work_dir + '/DEM/*.wgs84')[0]```

https://github.com/geodesymiami/rsmas_isce/blob/e868ce78451531520747482b47f085ce22606ee8/create_stacksentinel_run_files.py#L63

**Comment by falkamelung** [comment]
files2 will appear once we start using a different code for DEM generation.  So we better keep this.
