### ISSUE TITLE
run_operations.py bug

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#77]
Hi Josh, I tried to get run_operations to work using the bash version (as sxh733, for the pass: his first name is SangHoon).  It did something (It wrote GalapagosSenDT128 as a file instead of opening a directory), but then It failed. Any idea? I don’t know whether it is bash-related or something else. I suspect the latter. I did not run run_operations.py for a while so I don’t know when it broke. If needed I can test whether run_operations worked before switching to bash.

```
['GalapagosSenDT128', 'GalapagosSenAT106', 'KilaueaSenD87', 'KilaueaSenAT124', 'AgungSenDT32', 'AgungSenAT156', 'LombokSenDT32', 'LombokSenAT156', 'CotopaxiSenAT120', 'ChilesSenAT120', 'GalerasSenAT120']
Traceback (most recent call last):
  File "/nethome/sxh733/test/test1/rsmas_insar/sources/rsmas_isce/run_operations.py", line 336, in <module>
    ssaraopt = generate_ssaraopt_string(template_file=template_file)
  File "/nethome/sxh733/test/test1/rsmas_insar/sources/rsmas_isce/download_ssara_rsmas.py", line 74, in generate_ssaraopt_string
    template_options = Template(template_file).get_options()
  File "/nethome/sxh733/test/test1/rsmas_insar/sources/rsmas_isce/dataset_template.py", line 38, in __init__
    self.options = self.read_options(template_file)
  File "/nethome/sxh733/test/test1/rsmas_insar/sources/rsmas_isce/dataset_template.py", line 49, in read_options
    with open(template_file) as template:
NotADirectoryError: [Errno 20] Not a directory: '/projects/scratch/insarlab/sxh733/GalapagosSenDT128/GalapagosSenDT128.template'
```

**Comment by Ovec8hkin** [comment]
Could you please verify that /projects/scratch/insarlab/sxh733/GalapagosSenDT128/ exists? That’s what the error looks like at first glance.

**Comment by falkamelung** [comment]
The thing is run_operations.py creates a file with the name you mention. This file contains the template file contents
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Feb 25, 2019, at 1:55 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you pleaser verify that /projects/scratch/insarlab/sxh733/GalapagosSenDT128/ exists? That’s what the error looks like at first glance.
