### ISSUE TITLE
run_operations.py improvements

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#78]
- ability to digest multiple Google Sheets (so that we can have one GoogleSheet for each project).
- for ssaraopt we should use multiple options as in this Google Sheet (this works already, I think, but we should make this the standard).
https://docs.google.com/spreadsheets/d/1Q8isYbGtGLGBoeqIQffg-587K13MtrDoQTYnx_59fFE/edit#gid=1436095665
- understand  run_ops_endDate (needed for earthquake hazards project, currently there is no endDate) *template files will be located in an OPERATIONS/EARTHQUAKE_TEMPLATES) folder   
- need ability to run datasets every 6 days (satellite repeat cycle), 1,2,3,6,12 months (this was supposed to be done with the every_day_flag - need to think about a strategy.
- once everything is done we may want from a Google Sheet to something easier to manage

**Comment by falkamelung** [comment]
**run_operations_2.0.** 
Regarding the last bullet,  after Monday's presentation I now have a clearer idea. The information that is in the GoogleSheet could be in a database. We could have a web-based map and/or Google Sheet to modify it.

**Comment by Ovec8hkin** [comment]
Yes. A database would probably be ideal, but only after we get everything working appropriately with just the Google Sheets files. A database will also make life easier once we move to AWS.

**Comment by Ovec8hkin** [comment]
@falkamelung how do you want `run_operations` to deal with multiple Google Sheets? Should the sheets be specified over the command line, should they be hardcoded by default?

**Comment by falkamelung** [comment]
Multiple over the command line. We can put in the job file, right?

Sent from my IPhone.

On Mar 22, 2019, at 7:05 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


@falkamelung<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C95d823dd5890426bc3b108d6af2343ff%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636888963334004774&sdata=QZ7hMuHPF705LonBgE4RWzETbvSYmWGcafp2YUshgDE%3D&reserved=0> how do you want run_operations to deal with multiple Google Sheets? Should the sheets be specified over the command line, should they be hardcoded by default?

**Comment by Ovec8hkin** [comment]
So do you want it to be like this:
` generate_template_files.py --sheet1 ________  --sheet2 _______  --sheet3 _______ ...`

**Comment by falkamelung** [comment]
Yes. The idea is to have people first trying with their own google sheet file. Once it works we can run them all with the principal run operations

Sent from my IPhone.

On Mar 22, 2019, at 8:17 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


So do you want it to be like this:
generate_template_files.py --sheet1 ________ --sheet2 _______ --sheet3 _______ ...

**Comment by Ovec8hkin** [comment]
I don't understand what you mean. Should `run_operations`, by default, be run on multiple google sheets files, or is that an edge case that will only be used sometimes? If multiple sheets is the general case we only need the command line options to activate them for use. If they're the exception case, we have to be a little bit smarter about how we handle the template generations.

**Comment by falkamelung** [comment]
Yes, using multiple google sheet files. To be able to have thematic different sheet files. When a new area is ready we just add this in the run_operations.job file. And then we have the ability to run different areas on different platforms (I am aware that meaningful names like this one below don’t work, but maybe there is a way to do it?)

run_operations.py —sheet_id Ecuador_templates.csv. —sheet_id Hawaii_templates.csv —sheet_id India_landsubsidence_templates.csv —sheet_id EastCoast_landsubsidence.csv
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 22, 2019, at 10:50 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't understand what you mean. Should run_operations, by default, be run on multiple google sheets files, or is that an edge case that will only be used sometimes? If multiple sheets is the general case we only need the command line options to activate them for use. If they're the exception case, we have to be a little bit smarter about how we handle the template generations.

**Comment by Ovec8hkin** [comment]
Ok, thank you for the clarification. This is easy to implement when passing the sheet id from Google Sheets directly. There would be a way to be able to do it using meaningful names, but it would require that, for each new sheet you are using, you would have to update a dictionary in `run_operations` (or somewhere else), that maps the meaningful name to the sheet id. Something like below:

```
projects = {
     "Hawaii Templates": 111111111111111,
     "India_landsubsidence_templates": 1234567890987654321
     "EastCoast_landsubsidence": 2222222222222,
     ...
}
```

Then, when making the command line call you could specify the project name and then `run_operations` can look up the sheet id from the dictionary and use that to make the request and generate the template.

**Comment by falkamelung** [comment]
OK. I understand. Lets not bother with this now. If we move to a database instead of GoogleSheet it will be irrelevant. You could put some pseudo code/comment in, though, so that I know where it should go if I want to add it.
Falk
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 23, 2019, at 1:50 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, thank you for the clarification. This is easy to implement when passing the sheet id from Google Sheets directly. There would be a way to be able to do it using meaningful names, but it would require that, for each new sheet you are using, you would have to update a dictionary in run_operations (or somewhere else), that maps the meaningful name to the sheet id. Something like below:

projects = {
     "Hawaii Templates": 111111111111111,
     "India_landsubsidence_templates": 1234567890987654321
     "EastCoast_landsubsidence": 2222222222222,
     ...
}


Then, when making the command line call you could specify the project name and then run_operations can look up the sheet id from the dictionary and use that to make the request and generate the template.
