### ISSUE TITLE
Function in `_process_utilities.py` isn't used

### ISSUE THREAD

**Issue by gravelcycles** [geodesymiami/rsmas_insar#83]
https://github.com/geodesymiami/rsmas_isce/blob/bf0edaa937fe918bacd2b5ef434bacd0f9fa9ed6/_process_utilities.py#L496

Can `check_error_files_sentinelstack` be removed? It isn't used within `rsmas_isce`.
@falkamelung @mirzaees @lily-wittle @Ovec8hkin Please comment whether you have context or know where to look for usages on this. Please comment even if you have no context. Thanks <3

**Comment by falkamelung** [comment]
Keep it for now, please. It may have been replaced with something else but I don’t remember.
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 3, 2019, at 5:23 PM, David W Grossman <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/geodesymiami/rsmas_isce/blob/bf0edaa937fe918bacd2b5ef434bacd0f9fa9ed6/_process_utilities.py#L496<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeodesymiami%2Frsmas_isce%2Fblob%2Fbf0edaa937fe918bacd2b5ef434bacd0f9fa9ed6%2F_process_utilities.py%23L496&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Cc7933c09414140529ad508d6a026e8ec%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636872486321576101&sdata=q8zl9w6avqdYHpwqE27XV%2BxssF%2B%2BAuXlOL32Q4xJ%2BSI%3D&reserved=0>

Can check_error_files_sentinelstack be removed? It isn't used within rsmas_isce.
@falkamelung<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Cc7933c09414140529ad508d6a026e8ec%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636872486321586110&sdata=dCS%2FRnpAnPhGBROoZYVa9Ijs0pPQx2geexKm6fxTRuk%3D&reserved=0> @mirzaees<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmirzaees&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Cc7933c09414140529ad508d6a026e8ec%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636872486321586110&sdata=A4g0A2OMaYUgSu2wXcbOm2rfx2HluNdZ%2FVcbpY%2B6qeY%3D&reserved=0> @lily-wittle<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flily-wittle&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Cc7933c09414140529ad508d6a026e8ec%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636872486321596124&sdata=sabYhQhpwyEWC7AhgWmfLfjthGl8FZjCXx35uAXKVXc%3D&reserved=0> @Ovec8hkin<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOvec8hkin&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Cc7933c09414140529ad508d6a026e8ec%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636872486321596124&sdata=%2BAMbtIwL18wUjM1SYpb1o9gFBwou09FRJ48h1vWjQc0%3D&reserved=0> Please comment whether you have context or know where to look for usages on this. Please comment even if you have no context. Thanks <3
