### ISSUE TITLE
Move `check_for_operations_directories_and_initiate` to `run_operations`

### ISSUE THREAD

**Issue by gravelcycles** [geodesymiami/rsmas_insar#84]
This module is only called within `run_operations`. Any issue with moving the module into `run_operations`? @falkamelung @Ovec8hkin

**Comment by falkamelung** [comment]
No Issue. Move it, please.
Falk
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 3, 2019, at 5:26 PM, David W Grossman <notifications@github.com<mailto:notifications@github.com>> wrote:


This module is only called within run_operations. Any issue with moving the module into run_operations? @falkamelung<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C6170c127949f4376214708d6a0273848%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636872487646811332&sdata=j3j6wzVCKb6LR%2F30m%2FZ2AzCz7my86PyN%2Fos2lKaVWYs%3D&reserved=0> @Ovec8hkin<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOvec8hkin&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C6170c127949f4376214708d6a0273848%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636872487646811332&sdata=17YtTVPeh1rXkbcoyV3Gn5QowVROFkPxMamNUbkEtyA%3D&reserved=0>
