### ISSUE TITLE
Job submission --submit option 

### ISSUE THREAD

**Issue by lily-wittle** [geodesymiami/rsmas_insar#85]
"Hi Lily, the job submission in process_rsmas works fine. Thank you!  I added a similar option to download_rsmas.py. Could you please check and modofy if needed? The `project_name` variable is already taken. Would it be better to use `job_name`?  I am not sure we should use `inps.wall_time` and `inps.work_dir`. Should we just use `wall_time` and `work_dir`? David Grossman should know whether it is correct to use inps here or just for variable given on the command line when a script is called.  The next step would be to replace --bsub by --submit throughout the code. We also should use submit_flag instead of bsub_flag. Once we have sorted this out we are ready to add a --submit option to all major scripts."

**Comment by lily-wittle** [comment]
Note: have changed to using `job_name` and `job_file_name` as well as `--submit` and`submit_flag` and `--submit` option is now in `process_rsmas.py` and `download_rsmas.py` as of #86 

Still need to add `--submit` option to other major scripts. @falkamelung what are the other scripts needing this option?

**Comment by falkamelung** [comment]
For now download_ssara_rsmas ,   download_asfserial_rsmas.py

and

ingest_insarmaps.py


------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 8, 2019, at 3:49 PM, Lily Wittle <notifications@github.com<mailto:notifications@github.com>> wrote:


Note: have changed to using job_name and job_file_name as well as --submit andsubmit_flag and --submit option is now in process_rsmas.py and download_rsmas.py as of #86<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeodesymiami%2Frsmas_isce%2Fpull%2F86&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Cfb3f53e9acd14e23489808d6a40797b5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636876749857567039&sdata=m9xIDrDPvVhv29Akv%2BabrmeN3F3mS8%2B1DYFjh5uq5Os%3D&reserved=0>

Still need to add --submit option to other major scripts. @falkamelung<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Cfb3f53e9acd14e23489808d6a40797b5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636876749857567039&sdata=jTfDhDiXevqDXIU67z%2F7DbrFkhbv5dzvxrEeK%2BIHTvE%3D&reserved=0> what are the other scripts needing this option?
