### ISSUE TITLE
Centralize `run_operations.py` Logging and Log File Locations

### ISSUE THREAD

**Issue by Ovec8hkin** [geodesymiami/rsmas_insar#88]
Output log files from `run_operations.py` to a centralized directory for easy access and review. Ideally, this should take the form of a monolithic master log file (`run_operations.log`) in the $OPERATIONS/LOGS directory, but could also be written directly to the project workspace (ie. `/projects/scratch/insarlab/jaz101/KinneretSenDT21/run_operations.log`)

**Comment by Ovec8hkin** [comment]
@falkamelung Which of the above options would you like to see implemented. The monolithic log file is more standard within the software development industry but can be more difficult to filter through and find errors (@2gotgrossman or @Ovec8hkin can write something to help with that). Having a separate log in each project directory is a cleaner interface, but the logs are no longer centralized, which makes finding a bit more time consuming.

**Comment by falkamelung** [comment]
Not sure I understand. I thought we talked about it.  When it is called from run_operations it should end up in the OPERATIONS/LOG. When it is not called from run_operations it should be in the project_directory and when a run is complete the log file will be moved into the OPERATIONS/LOG directory.   I have no problem to have multiple log files instead of a monolithic one. I guess once we are fully in operations we could switch to a monolithic one but I don't see an advantage compared to multiple smaller ones. Actually, the multiple smaller onces are easier to handle as files older than, say, 6 month coule be easily removed.

**Comment by falkamelung** [comment]
Or we have an option in process_rsmas.py to select the log file?  It could be  process_rsmas.py —operations to write to OPERATIONS/LOG and this would be the call in run_operations.py
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 6, 2019, at 8:33 AM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


@falkamelung<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C7dc01d1fb0db4b78278e08d6a23851d6%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636874760106424623&sdata=4aNfQmMeyiV%2FRJEFwgjodHyu85HpvxuX6cqKvWWniRI%3D&reserved=0> Which of the above options would you like to see implemented. The monolithic log file is more standard within the software development industry but can be more difficult to filter through and find errors (@2gotgrossman<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F2gotgrossman&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C7dc01d1fb0db4b78278e08d6a23851d6%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636874760106434632&sdata=rUqGWpQSynzELfz2zLoghMXoi3GqSjM9wkOa%2Frrkgf4%3D&reserved=0> or @Ovec8hkin<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOvec8hkin&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C7dc01d1fb0db4b78278e08d6a23851d6%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636874760106434632&sdata=4W99%2BhWz5IFaf5VgJLY8KNtrB0Jv5g2C7viJJqO2d%2Fs%3D&reserved=0> can write something to help with that). Having a separate log in each project directory is a cleaner interface, but the logs are no longer centralized, which makes finding a bit more time consuming.
